### ISSUE TITLE
Memory leak in LiteDB.LiteFileStorage.Download()

### ISSUE THREAD

**Issue by maseal** [mbdavid/LiteDB#102]
I've uploaded 500 files to FileStorage (average filesize ~5Mb), than just tried to download all files from FileStorafe with this code:
```csharp
foreach (var fileInfo in db.FileStorage.FindAll())
{
  var outFilename = Guid.NewGuid().ToString("N") + fileInfo.Id;
  using (FileStream outStream = new FileStream(outFilename, FileMode.CreateNew))
  {
    db.FileStorage.Download(fileInfo.Id, outStream);
  }
}
```
Application ate about 2Gb memory and I got OutOfMemoryException:
```
Test method LiteDB.AppTest.DownloadAll threw exception: 
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
    at System.IO.MemoryStream.ToArray()
   at LiteDB.DataService.ReadExtendData(UInt32 extendPageID) in c:\Projects\LiteDB\LiteDB\DbEngine\Services\DataService.cs:line 143
   at LiteDB.DataService.Read(PageAddress blockAddress, Boolean readExtendData) in c:\Projects\LiteDB\LiteDB\DbEngine\Services\DataService.cs:line 124
   at LiteDB.DbEngine.<Find>d__d.MoveNext() in c:\Projects\LiteDB\LiteDB\DbEngine\Actions\Find.cs:line 34
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteFileStream.GetChunkData(Int32 index) in c:\Projects\LiteDB\LiteDB\FileStorage\LiteFileStream.cs:line 78
   at LiteDB.LiteFileStream..ctor(DbEngine engine, LiteFileInfo file) in c:\Projects\LiteDB\LiteDB\FileStorage\LiteFileStream.cs:line 31
   at LiteDB.LiteFileInfo.OpenRead() in c:\Projects\LiteDB\LiteDB\FileStorage\LiteFileInfo.cs:line 131
   at LiteDB.LiteFileInfo.CopyTo(Stream stream) in c:\Projects\LiteDB\LiteDB\FileStorage\LiteFileInfo.cs:line 152
   at LiteDB.LiteFileStorage.Download(String id, Stream stream) in c:\Projects\LiteDB\LiteDB\FileStorage\LiteFileStorage.cs:line 101
```
version: https://github.com/mbdavid/LiteDB/commit/945986b025de9e97315bc6fac5309488e5c883c3

**Comment by mbdavid** [comment]
Hi @maseal, I found the problem. Cache recicle is based on pages count used in memory. After 5000 pages in memory. LiteDB clear all cache. But, I forgot that FileStorage use DataPage to store all ExtendPages data. So, each DataPage can have 200 blocks, each one with 5Mb each.

I will fix this this weekend (and another problems). For now, you can:
- Change cache limit to 20 pages only (DbEngine\Services\CacheService.cs -> MAX_CACHE_SIZE)
- Open/Close database after each download, like:

```C#
string[] files;

using (var db = new LiteDatabase(filedb))
{
    files = db.FileStorage.FindAll().Select(x => x.Id).ToArray();
}

foreach(var id in files)
{
    using (var db = new LiteDatabase(""))
    {
        var outFilename = Guid.NewGuid().ToString("N") + id;

        using (var outStream = new FileStream("filename", FileMode.CreateNew))
        {
            db.FileStorage.Download(id, outStream);
        }
    }
}
```

I will fix this bug probably this weekend.

**Comment by mbdavid** [comment]
Hi @maseal, please, do another test. On my unit test is ok now.

**Comment by maseal** [comment]
I've tested with the latest commit (https://github.com/mbdavid/LiteDB/commit/80a81208d465d3d32b9fcf02ff155fbec5206caf) and it looks like memleak problem fixed.
Now the same application use not more than 40Mb in RAM.
