### ISSUE TITLE
System.NotSupportedException: 'Stream does not support writing.'

### ISSUE THREAD

**Issue by mciureanu** [mbdavid/LiteDB#1022]
Doing multiple reads on multiple threads with only read access, and in the same time doing writes
on multiple threads gets to this exception in the read thread:

With journaling disabled, everything seems fine. Probably it's related to the fact that journal manipulation is done from the read thread, or something like this....

   at System.IO.FileStream.SetLength(Int64 value)
   at LiteDB.FileDiskService.SetLength(Int64 fileSize) in C:\Projects\Tests\LiteDB-4.1.4\LiteDB\Engine\Disks\FileDiskService.cs:line 143
   at LiteDB.FileDiskService.ClearJournal(UInt32 lastPageID) in C:\Projects\Tests\LiteDB-4.1.4\LiteDB\Engine\Disks\FileDiskService.cs:line 230
   at LiteDB.TransactionService.Recovery() in C:\Projects\Tests\LiteDB-4.1.4\LiteDB\Engine\Services\TransactionService.cs:line 144
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate) in C:\Projects\Tests\LiteDB-4.1.4\LiteDB\Engine\LiteEngine.cs:line 143
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0() in C:\Projects\Tests\LiteDB-4.1.4\LiteDB\Database\LiteDatabase.cs:line 79
   at LiteDB.LazyLoad`1.get_Value() in C:\Projects\Tests\LiteDB-4.1.4\LiteDB\Utils\LazyLoad.cs:line 30
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext() in C:\Projects\Tests\LiteDB-4.1.4\LiteDB\Database\Collections\Find.cs:line 19
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindOne(Expression`1 predicate) in C:\Projects\Tests\LiteDB-4.1.4\LiteDB\Database\Collections\Find.cs:line 67

Forgot to mention: I use the db in shared process mode with all writes and reads with "using new LiteDb,,, "

**Comment by mbdavid** [comment]
Hi @mciureanu, do you have a code snippet so I can reproduce tests here? Maybe can be a write lock problem.

**Comment by stitch10925** [comment]
Hey @mciureanu,

I hit upon this article today: https://github.com/mbdavid/LiteDB/wiki/Concurrency

It states that you should only open one instance of the database and that your processes should then use this shared instance for reading and writing. I tried it and did not get any IO errors anymore. The drawback is that reading, at least for me, seemed to be very slow while simultaneously writing to the database.

The documentation also mentions an exclusive mode to put in the connection string (mode=Exclusive), but then you really need to make sure that you only have a single process accessing the database or it will throw an error that the file is in use by another process.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
