### ISSUE TITLE
Error Access db When Create Setup file

### ISSUE THREAD

**Issue by MohMehrnia** [mbdavid/LiteDB#1031]
Hello,
I Created a Setup Project and add Litedb (app.db) to them and i install in c:\program files(x86), now when run application show me a below error message
Application: AIKI.CO.VideoProtector.UI.Publisher.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions)
   at LiteDB.FileDiskService.Initialize(LiteDB.Logger, System.String)
   at LiteDB.LiteEngine..ctor(LiteDB.IDiskService, System.String, System.Nullable`1<System.TimeSpan>, Int32, LiteDB.Logger, Boolean)
   at LiteDB.LiteDatabase+<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at LiteDB.LiteCollection`1+<Find>d__17[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at LiteDB.LiteQueryable`1+<ToEnumerable>d__21[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at LiteDB.LiteQueryable`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FirstOrDefault()
   at AIKI.CO.VideoProtector.Model.Repository`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetSingle(System.Linq.Expressions.Expression`1<System.Func`2<System.__Canon,Boolean>>)
   at AIKI.CO.VideoProtector.Presenters.AppSettingPresenter.IsTitleExists()
   at AIKI.CO.VideoProtector.UI.Publisher.frmMain..ctor()
   at AIKI.CO.VideoProtector.UI.Publisher.Program.Main()

**Comment by toumir** [comment]
its good if you provide us more details,
any way from the stack trace **Exception Info: System.UnauthorizedAccessException**
try to put the app.db file to another partition other then c:\ drive
