### ISSUE TITLE
System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by AntonSemenovKazan** [mbdavid/LiteDB#1115]
**LiteDB: 4.1.2.0**

I think you have rude and simple bug with stacktrace:

```
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at LiteDB.Logger.Write(Byte level, String message, Object[] args)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
```

It happens here:
```
      // ISSUE: reference to a compiler-generated field
      if (((int) level & (int) this.Level) == 0 || string.IsNullOrEmpty(message) || this.Logging == null)
        return;
      string str1 = string.Format(message, args);
```

You pass into template ex.Message .
And it is easy to have incorrect format there.

I have custom simple logging (means logging Action is not null) and level = Error.
Thus I mean string.Format could be achieved.

I have caught exception in production.

More over I cannot work with LiteDb at all further.
After this expection always appears showed below.
It looks like corrupted DB.

```
System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindById(BsonValue id)
```

**Also** I have noticed that you have many issues with corrupted DB, here could be reason.
Cause If first exception happens we lose perfoming this._cache.DiscardDirtyPages();

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
