### ISSUE TITLE
LiteCollection.FindById throws a NullReferenceException

### ISSUE THREAD

**Issue by jakedacatman** [mbdavid/LiteDB#1234]
When trying to get an instance of my custom class GuildQueue from the collection, a nullref is thrown. Here is its stack trace:  
 at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject(Type type, BsonDocument doc)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection\`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable\`1 source)
   at LiteDB.LiteCollection\`1.FindById(BsonValue id)

**Comment by lobster2012-user** [comment]
Hi @jakedacatman !
Could you give the link not a ready demo for the link?

**Comment by Brannos1970** [comment]
Can you show your code? I had the same problem and found a mistake in my code.

**Comment by JensSchadron** [comment]
@jakedacatman Has your issue been resolved in the meantime?
If so, could you please close this issue?
If it isn't, could you provide us with some code that shows the issue as some of us suspect that it's an accidental issue in the code on your end 😅
