### ISSUE TITLE
"datafile must be released" error whilst inserting large List

### ISSUE THREAD

**Issue by omfgicbf** [mbdavid/LiteDB#1270]
With V5 (master 203edef)

When inserting 1 million records via a List, a debug assert fails.

~~Inserting 100,000 or lower works OK.~~ (had it happen with 100,000 also)

```
static void Main(string[] args)
{
    var file = @"test.litedb";

    using (var db = new LiteDatabase($"{file}"))
    {
        var col = db.GetCollection<Event>("event");

        try
        {
            var tmp = new List<Event>();

            for (var i = 0; i < 1_000_000; i++)
            {
                tmp.Add(new Event()
                {
                    Data = "the quick brown fox jumps over the lazy dog",
                    DateTime = DateTime.Now
                });
            }

            col.Insert(tmp);
        }
        catch (Exception ex)
        {
            throw ex;
        }

        db.Checkpoint();
    }

    Console.WriteLine("Done");

    Console.ReadLine();
}
```

Results:-
```
1|ENGINE: start initializing
1|CACHE: extending memory usage: (segments: 1 - used: 7.8MB)
1|DISK: creating new database: 'test.litedb'
1|ENGINE: initialization completed
1|COMMAND: insert `event`
1|CACHE: extending memory usage: (segments: 2 - used: 15.6MB)
1|CACHE: extending memory usage: (segments: 3 - used: 23.4MB)
1|CACHE: extending memory usage: (segments: 4 - used: 31.2MB)
1|CACHE: extending memory usage: (segments: 5 - used: 39.1MB)
1|CACHE: extending memory usage: (segments: 6 - used: 46.9MB)
1|CACHE: extending memory usage: (segments: 7 - used: 54.7MB)
1|CACHE: extending memory usage: (segments: 8 - used: 62.5MB)
1|CACHE: extending memory usage: (segments: 9 - used: 70.3MB)
1|CACHE: extending memory usage: (segments: 10 - used: 78.1MB)
1|CACHE: extending memory usage: (segments: 11 - used: 85.9MB)
1|CACHE: extending memory usage: (segments: 12 - used: 93.8MB)
1|CACHE: extending memory usage: (segments: 13 - used: 101.6MB)
1|CACHE: extending memory usage: (segments: 14 - used: 109.4MB)
1|CACHE: extending memory usage: (segments: 15 - used: 117.2MB)
1|CACHE: extending memory usage: (segments: 16 - used: 125MB)
1|CACHE: extending memory usage: (segments: 17 - used: 132.8MB)
1|CACHE: extending memory usage: (segments: 18 - used: 140.6MB)
1|CACHE: extending memory usage: (segments: 19 - used: 148.4MB)
1|CACHE: extending memory usage: (segments: 20 - used: 156.2MB)
1|CACHE: extending memory usage: (segments: 21 - used: 164.1MB)
1|CACHE: extending memory usage: (segments: 22 - used: 171.9MB)
1|CACHE: extending memory usage: (segments: 23 - used: 179.7MB)
1|CACHE: extending memory usage: (segments: 24 - used: 187.5MB)
1|CACHE: extending memory usage: (segments: 25 - used: 195.3MB)
1|CACHE: extending memory usage: (segments: 26 - used: 203.1MB)
1|CACHE: extending memory usage: (segments: 27 - used: 210.9MB)
1|CACHE: extending memory usage: (segments: 28 - used: 218.8MB)
1|CACHE: extending memory usage: (segments: 29 - used: 226.6MB)
1|TRANSACTION: commit transaction (28844 pages)
1|WAL: checkpoint
1|DISK: disposing disk writer queue (with 0 pages in queue)
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
datafile must be released
---- Assert Long Message ----

   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.DiskService.Dispose()
   at LiteDB.Engine.LiteEngine.Dispose(Boolean disposing)
   at LiteDB.Engine.LiteEngine.Dispose()
   at LiteDB.LiteDatabase.Dispose()
   at LiteDBEnsureIndexTest.Program.Main(String[] args) in D:\Dropbox\Development\LiteDBEnsureIndexTest\LiteDBEnsureIndexTest\Program.cs:line 62
```

**Comment by JensSchadron** [comment]
@omfgicbf Weirdly enough, I cannot reproduce the given result myself. Could you give us a bit more information about the environment in which LiteDB is used. (OS, runtime, et cetera? )

On my end, I'm using
OS: OSX 10.14.6
.NET Runtime: 2.2.5
.NET SDK Version: 2.2.300

The demo project is running as .NETCoreApp 2.2

**Comment by JensSchadron** [comment]
After some thorough testing (with and without commit 6e467de), I can't reproduce the bug.

**Comment by mbdavid** [comment]
Hi @omfgicbf, are you running over Dropbox directory? Try use a "normal" directory. This assert (that occurs only in DEBUG mode) test if file, after use, is completed released by LiteDB.... but not only LiteDB, if dropbox are reading this file will detect as open file too.

I tried in Windows 10, .NET 46 in SSD.... no assert fail found

**Comment by omfgicbf** [comment]
Hi @mbdavid, I have re-tested outside of Dropbox directory and the error is no longer thrown. Thanks.
