### ISSUE TITLE
LiteRepository failed but  LiteRepository.Database  success?

### ISSUE THREAD

**Issue by git-net** [mbdavid/LiteDB#1277]
netcore 2  consoleapp nuget 4.1.4
 
```
var repo = new LiteRepository(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "local.local"));
            var d = new TestObj[] { new TestObj { Id = 1, Name = "123" } };
            try
            {
                repo.Database.GetCollection<TestObj>(null).Upsert(d);//success
                repo.Upsert(d);//failed why?
            }
            catch (Exception ex)
            {

                
            }   
```
here TestObj
```
 public class TestObj {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
    }
```

**Comment by git-net** [comment]
errors
Object reference not set to an instance of an object.
   at LiteDB.BsonMapper.ToDocument[T](T entity)
   at LiteDB.LiteCollection`1.<GetBsonDocs>d__38.MoveNext()
   at LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteCollection`1.Upsert(T document)
   at ConsoleApp1.Program.Main(String[] args) in  ConsoleApp1\Program.cs:line 19

**Comment by git-net** [comment]
I know .
repo apis has two  Upsert
bool Upsert<T>(T entity, string collectionName = null)
int Upsert<T>(IEnumerable<T> entities, string collectionName = null)
so need repo.Upsert<T>(d);
close .but this not a good api
