### ISSUE TITLE
LiteDB.CacheService.RemoveExtendPages throws "System.InvalidOperationException: Collection was modified after the enumerator was instantiated."

### ISSUE THREAD

**Issue by mykemaas** [mbdavid/LiteDB#13]
I created a quick sample application that stores a number of jpg images using FileStorage.  The application is a web application that exposes an endpoint where the images can be downloaded.  I created a sample web page that references a number of the images I have stored.  When the requests hit the endpoint simultaneously, just about every other request throws this exception:

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   at System.Collections.Generic.SortedDictionary`2.Enumerator.MoveNext()
   at System.Collections.Generic.SortedDictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LiteDB.CacheService.RemoveExtendPages()
   at LiteDB.LiteFileStream.GetChunkData(Int32 index)
   at LiteDB.LiteFileStream..ctor(LiteEngine engine, FileEntry entry)
   at LiteDB.FileEntry.OpenRead()

I am guessing here, but it looks like RemoveExtendPages method doesn't have a lock on the collection it is enumerating?

**Comment by mbdavid** [comment]
Hi @mykemaas, are using database in a `using` statement? LiteDB is not thread safe (at lease for now). So, you need always open/close database per request/use - in this case, cache memory are in each database instance. Is this case? Can you post part of your source?

**Comment by mykemaas** [comment]
Yeah... That's my mistake... I'll change it and test.  Thanks!

**Comment by mbdavid** [comment]
Nice! LiteDB is not thread safe, but is "process safe". You can have concurrent open databases instances.
