### ISSUE TITLE
Database creation 5.0.0-alpha

### ISSUE THREAD

**Issue by lxman** [mbdavid/LiteDB#1307]
I am attempting to use a pattern in my program of using a single class per database for a data access layer. The basic pattern of the classes is illustrated with the following:
```
    internal class FirmDB : IDisposable
    {
        private readonly LiteDatabase Database;
        private readonly LiteCollection<Firm> Firms;
        private readonly bool ReadOnly;
        private bool disposedValue = false;

        #region Public Interface

        public FirmDB(bool readOnly = false)
        {
            ConnectionString connStr = new ConnectionString
            {
                Filename = Constants.FirmSpec,
                Password = Constants.FirmPW,
                ReadOnly = readOnly
            };
            Database = new LiteDatabase(connStr);
            Firms = Database.GetCollection<Firm>();
            if (!Database.CollectionExists(nameof(Firm))) Firms.EnsureIndex(f => f.Id);
            ReadOnly = readOnly;
        }

        public BsonValue Create(string firmName, PersonName repName, IAddress address)
        {
            if (ReadOnly) return null;
            if (Firms.Count() > 0) Delete(Firms.FindAll().FirstOrDefault());
            return Firms.Insert(new Firm
            {
                BusinessName = firmName,
                FirmRep = repName,
                Address = address
            });
        }

        public Firm Read()
        {
            return Firms.FindAll()?.FirstOrDefault();
        }

        public bool Update(Firm f)
        {
            if (ReadOnly) return false;
            return Firms.Update(f);
        }

        public bool Delete(Firm f)
        {
            if (ReadOnly) return false;
            return Firms.Delete(f.Id);
        }

        #endregion Public Interface

        #region IDisposable Support

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    Database.Dispose();
                }

                disposedValue = true;
            }
        }

        // This code added to correctly implement the disposable pattern.
        public void Dispose()
        {
            Dispose(true);
        }

        #endregion IDisposable Support
    }
```
When I need to access the database, it is via a using statement like so:
```
            using (FirmDB db = new FirmDB())
            {
                // do stuff
            }
```
My issue is occurring when the physical file does not exist on the disk. The instantiation procedure is a bit unclear to me. I had thought that calling `GetCollection<T>` would be enough to cause the file to appear. According to the documentation that I can find, that does not appear to be the case. One must also call `EnsureIndex` as well.
This works well for the first database I create (a different class, `UsersDB`, though of the same form). On attempting to instantiate the first instance of `ProgramOptionsDB` I am met with an error:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not find file 'C:\ProgramData\AccountingApp\AccountingApp\1.0.0.0\ProgramOptions.db'.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LiteDB.Engine.DiskService..ctor(EngineSettings settings)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LiteDB.LiteCollection`1.Query()
   at LiteDB.LiteDatabase.GetCollectionNames()
   at LiteDB.LiteDatabase.CollectionExists(String name)
   at AccountingApp.Databases.ProgramOptionsDB..ctor(Boolean readOnly) in C:\Users\michael\source\repos\AccountingClasses\AcctClasses\AccountingApp\Databases\ProgramOptionsDB.cs:line 27
   at AccountingApp.Controls.CtlFirm..ctor() in C:\Users\michael\source\repos\AccountingClasses\AcctClasses\AccountingApp\Controls\CtlFirm.cs:line 26
   at AccountingApp.FrmMain.TvNavigate_BeforeSelect(Object sender, TreeViewCancelEventArgs e) in C:\Users\michael\source\repos\AccountingClasses\AcctClasses\AccountingApp\FrmMain.cs:line 58
   at System.Windows.Forms.TreeView.OnBeforeSelect(TreeViewCancelEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelecting(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.Control.ReflectMessageInternal(IntPtr hWnd, Message& m)
   at System.Windows.Forms.Control.WmNotify(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.TreeView.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at AccountingApp.Program.Main() in C:\Users\michael\source\repos\AccountingClasses\AcctClasses\AccountingApp\Program.cs:line 16
```
As succinctly as possible, here is what I am observing while debugging:

When I arrive at the `if (!Database.CollectionExists(nameof(UsersDB)))` line when creating the `UsersDB` (the one that succeeds), the physical file on disk does not exist yet. After stepping through that statement and before executing the `EnsureIndex` following it, I see one file, `Users.db` of size zero bytes. On executing the `EnsureIndex` I see two files, the original `Users.db` and another, `Users-log.db`, both of size zero bytes. This state continues until I finally exit the using statement that originally called the constructor and I now have a single file, `Users.db` of size 40k. Opening the database in LiteDB Studio shows that it does appear to contain the information I stored there.

At a later point in my process, I have entered a separate using statement for my `ProgramOptionsDB` class. I hit the `if (!Database.CollectionExists(nameof(ProgramOptionsDB)))` line, and if I try to step past it, the file is not created and I receive the error above.

**Comment by lxman** [comment]
Ah, okay, found the issue. I am still a bit puzzled about the best way to overcome this, however.

I was calling my constructor like this:
```
            using (ProgramOptionsDB db = new ProgramOptionsDB(true))
            {
                TbDataDir.Text = db.GetDataDir(RuntimeGlobals.CurrentUserGuid);
            }
```
As I am only reading a value out of the database, this seemed perfectly okay. However, if the physical file on disk does not exist yet, `LiteDB` fails when creating the file, due to the readonly setting.
For the time being, I have modified my constructors to the following form, which appears to work.
```
        internal ProgramOptionsDB(bool readOnly = false)
        {
            ConnectionString connStr = new ConnectionString
            {
                Filename = Constants.ProgramOptionsSpec,
                Password = Constants.ProgramOptionsPW,
                ReadOnly = (File.Exists(Constants.ProgramOptionsSpec)) ? readOnly : false
            };
            Database = new LiteDatabase(connStr);
            Options = Database.GetCollection<ProgramOptions>();
            ReadOnly = readOnly;
        }
```
For the sake of discussion, the reason I am using a `ConnectionString` instead of a `LiteEngine` and `EngineSettings` is I want to be able to have the option of setting the `Mode` option in the future. With `EngineSettings` I do not see a way to access this property. Is there some way to set the `Mode` using `EngineSettings`?
