### ISSUE TITLE
DateTime as dictionary key not serialized correctly.

### ISSUE THREAD

**Issue by PassiveModding** [mbdavid/LiteDB#1350]
https://github.com/mbdavid/LiteDB/blob/f568f133077dc24d2b74fb7b23f1bf64e042706d/LiteDB/Client/Mapper/BsonMapper.Deserialize.cs#L252

```
String '26/08/2019 6:57:26 AM' was not recognized as a valid DateTime.
System.FormatException: String '26/08/2019 6:57:26 AM' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at LiteDB.BsonMapper.DeserializeDictionary(Type K, Type T, IDictionary dict, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at RavenBOT.ELO.Modules.Modules.Info.LeaderboardAsync()
```

It appears when using a datetime as a key for a dictionary stored the parser does not convert it into a litedb format but rather leaves it as a string

**Comment by PassiveModding** [comment]
I suppose the root of the issue is in the https://github.com/mbdavid/LiteDB/blob/0412d11ed9492bd0e442db3e18b195b164bf5ca9/LiteDB/Client/Mapper/BsonMapper.Serialize.cs#L159 method then as it just sets the 'index' of the value to be `key.ToString()`.

**Comment by PassiveModding** [comment]
Basically  a dupe of https://github.com/mbdavid/LiteDB/issues/546

**Comment by mbdavid** [comment]
Hi @PassiveModding, I think if this `key.ToString()` contains a special format for `DateTime` (like ISO-8601) will be possible to revert from string to datetime.

**Comment by PassiveModding** [comment]
@mbdavid thanks, yes that would work. Are there any plans to have a generic method of serializing classes to work as keys by any chance?

**Comment by mbdavid** [comment]
In dictionary, keys must be a `String` type because are serialized as JSON document (each Key will be converted into a Field, and fields must be a string).
