### ISSUE TITLE
[v 4.1.4] Timeout.DataBase is locked for more than 00:01:00.

### ISSUE THREAD

**Issue by DannyCKing** [mbdavid/LiteDB#1356]
This has been really killing an application I've created using LiteDB.  I've seen others with this issue - but their solutions don't seem related to what I am doing.  

See below for a stack trace.  When this happens we are pounding the database fairly hard(dozens of times per second possibly) with the below code:

Any guidance is appreciated. This is really causing some headaches right now.  

```
                MyModel newModel = new MyModel { Name = "Steve"};
		using (var db = new LiteDatabase(MY_DATABASE))
                {
                    // Get a collection (or create, if doesn't exist)
                    var col = db.GetCollection<MyModel>(MY_COLLECTION);

                    var result = col.FindOne(x => x.Name== newModel.Name);
                    if(result == null)
                    {
                        col.Insert(model);
                    }
                    else
                    {
		        result.Name "Blah";
                        col.Update(result);
                    }
                }
```

And the stack trace:

> 2019-10-28 08:31:33.341 Error on adding to the databse.   Timeout. Database is locked for more than 00:01:00.    at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
>    at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
>    at LiteDB.FileDiskService.Lock(LockState state, TimeSpan timeout)
>    at LiteDB.LockService.Write()
>    at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
>    at LiteDB.LiteEngine.Update(String collection, IEnumerable`1 docs)
>    at LiteDB.LiteCollection`1.Update(T document)

**Comment by DannyCKing** [comment]
Possible update:

My best theory is that Windows Defender(or some other anti virus software) is scanning my database file every once in awhile.  

When I manually start a scan in Windows Defender of the folder containing my database file - I can replicate this fairly easily.  

I am probably going to close this - but hope it helps someone else seeing this issue.
