### ISSUE TITLE
LiteDB.LiteException: 'Collection 'nameOfCollection' lock timeout when entering in reserved mode after 00:01:00

### ISSUE THREAD

**Issue by mincasoft** [mbdavid/LiteDB#1432]
LiteDB.LiteException
  HResult=0x80131500
  Message=Collection 'UserAccount' lock timeout when entering in reserved mode after 00:01:00
  Source=LiteDB
  StackTrace:
   at LiteDB.Engine.LockService.EnterReserved(String collectionName)
   at LiteDB.Engine.Snapshot..ctor(LockMode mode, String collectionName, HeaderPage header, UInt32 transactionID, TransactionPages transPages, LockService locker, WalIndexService walIndex, DiskReader reader, Boolean addIfNotExists)
   at LiteDB.Engine.TransactionService.<CreateSnapshot>g__create|38_0(<>c__DisplayClass38_0& )
   at LiteDB.Engine.TransactionService.CreateSnapshot(LockMode mode, String collection, Boolean addIfNotExists)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass26_0.<Update>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Update(String collection, IEnumerable`1 docs)
   at LiteDB.LiteCollection`1.Update(T entity)
   at LiteDB.LiteRepository.Update[T](T entity, String collectionName)
   at ViettelIM.Core.Persistence.Repositories.UserAccountRepository.Update(UserAccount resource) in D:\Projects\CSharp\Desktop app\Viettel Change SIM AI\ViettelIM.Core\Persistence\Repositories\UserAccountRepository.cs:line 35
   at ViettelIM.Core.Services.UserAccountService.<>c__DisplayClass5_0.<UpdateAsync>b__0() in D:\Projects\CSharp\Desktop app\Viettel Change SIM AI\ViettelIM.Core\Services\UserAccountService.cs:line 98
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

  This exception was originally thrown at this call stack:
	LiteDB.Engine.LockService.EnterReserved(string)
	LiteDB.Engine.Snapshot.Snapshot(LiteDB.Engine.LockMode, string, LiteDB.Engine.HeaderPage, uint, LiteDB.Engine.TransactionPages, LiteDB.Engine.LockService, LiteDB.Engine.WalIndexService, LiteDB.Engine.DiskReader, bool)
	LiteDB.Engine.TransactionService.CreateSnapshot.__create|38_0(ref LiteDB.Engine.TransactionService.<>c__DisplayClass38_0)
	LiteDB.Engine.TransactionService.CreateSnapshot(LiteDB.Engine.LockMode, string, bool)
	LiteDB.Engine.LiteEngine.Update.AnonymousMethod__0(LiteDB.Engine.TransactionService)
	LiteDB.Engine.LiteEngine.AutoTransaction<T>(System.Func<LiteDB.Engine.TransactionService, T>)
	LiteDB.Engine.LiteEngine.Update(string, System.Collections.Generic.IEnumerable<LiteDB.BsonDocument>)
	LiteDB.LiteCollection<T>.Update(T)
	LiteDB.LiteRepository.Update<T>(T, string)
    ViettelIM.Core.Persistence.Repositories.UserAccountRepository.Update(ViettelIM.Core.Domain.Models.UserAccount) in UserAccountRepository.cs
    ...
    [Call Stack Truncated]

**Comment by mbdavid** [comment]
You are not keeping a transaction open? Or a query IEnumerable without dispose?

**Comment by Andrey-N** [comment]
I got same error on a pretty easy code and in this issue too https://github.com/mbdavid/LiteDB/issues/1431
Downgrade to 5.0RC version fix all and work great, for me

**Comment by lbnascimento** [comment]
@mincasoft Could you test it with v5.0.1?

**Comment by DevShip** [comment]
> You are not keeping a transaction open? Or a query IEnumerable without dispose?

Faced the same problem without dispose, for me an increase to v5.0.1 solved the problem.

**Comment by Andrey-N** [comment]
5.0.1 solved the problem for me

**Comment by JensSchadron** [comment]
Closing the issue as it has been resolved by updating to 5.0.1

**Comment by behroozbc** [comment]
hi 
I get same error in 
5.0.10 
```{"Collection 'SerialPortData' lock timeout when entering in write mode after 00:01:00"}```

**Comment by FelixLorenz** [comment]
I have had a similar issue (probably).

Exception was:

`Collection 'MyCollection' lock timeout when entering in write mode after 00:01:00`

... thrown by the same logic that was rock stable when awaited from the UI synchronization context. But as soon as a SignalR handler tried to execute this method these exception occured. Looks like in your stack trace, that the DB calls were also done from a different synchronization context.

Manually awaiting this method from the UI synchronization context again fixed all issues immediately. Like so:

```
private void MySignalrEventHandler()
{
    Task.Factory.StartNew(
        async () =>
        {
            await MyUsuallyRockstableMethod(); // executing up to thousands of upserts on tens of collections
        },
        CancellationToken.None,
        TaskCreationOptions.None,
        taskSchedulerForDesiredSyncContext // eg get via TaskScheduler.FromCurrentSynchronizationContext(); while on UI thread and pass around
        ); 
}
```

Hope it helps!
