### ISSUE TITLE
[BUG] Expression IIF(X, IfTrue, IfFalse) evaluates both IfTrue and IfFalse

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1458]
**Version**

LiteDB 5.0.1 and the latest from repo, Windows 10, net45

**Describe the bug**

In the expression `IIF(X, IfTrue, IfFalse)`, both `IfTrue` and `IfFalse` seem to be evaluated.

As a result, evaluation of one of them may fail when `X` is supposed to avoid this evaluation with invalid arguments.

**Code to Reproduce**

```csharp
var ex1 = BsonExpression.Create("IIF(LENGTH($.x) >= 5, SUBSTRING($.x, 0, 5), \"too-short\")");
var doc1 = new BsonDocument();

// OK ("12345")
doc1["x"] = "123456789";
var r1 = ex1.ExecuteScalar(doc1);
Console.WriteLine($"{r1}");

// KO (expected: "too-short", actual: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.)
doc1["x"] = "123";
var r2 = ex1.ExecuteScalar(doc1);
Console.WriteLine($"{r2}");
```

**Expected behavior**

See code comments.

**Screenshots/Stacktrace**

Output of the above code:

```
"12345"

Unhandled Exception: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at LiteDB.BsonExpressionMethods.SUBSTRING(BsonValue value, BsonValue startIndex, BsonValue length)
   at lambda_method(Closure , IEnumerable`1 , BsonDocument , BsonValue , Collation , BsonDocument )
   at LiteDB.BsonExpression.ExecuteScalar(IEnumerable`1 source, BsonDocument root, BsonValue current, Collation collation)
   at LiteDB.BsonExpression.ExecuteScalar(BsonDocument root, Collation collation)
```

**Comment by mbdavid** [comment]
Hi @nightroman, same problem in AND/OR logical test. Upgrade to use `Expression.Conditional` linq expression. Thanks!
