### ISSUE TITLE
[BUG] Nullable type support does not work in V5.0.2 and dotnetcore 3.1 linux docker

### ISSUE THREAD

**Issue by seertenedos** [mbdavid/LiteDB#1492]
**Version**
LiteDB 5.0.2 running in linux docker using dotnet core 3.1
**Describe the bug**
When using a nullable type like Guid? in dotnet core an error is thown to say "There is no _id field mapped in your type: System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" In the past we had a similar issue in another app we used with System.String source dll is different between dotnet and dotnet core so you can only match on the classname and namespace.

**Code to Reproduce**
using this class
public class VirtualPath
    {
        public string Id { get; set; }
        public Guid? File { get; set; }
        public Guid? Directory { get; set; }
    }
try to insert
_pathsCollection.Insert(new VirtualPath() { Id = "/", Directory = Guid.New()});

**Expected behavior**
The record be inserted and File would be null or not on the document

**Screenshots/Stacktrace**
LiteDB.LiteException: There is no _id field mapped in your type: System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
   at LiteDB.BsonMapper.<>c__DisplayClass48_0.<RegisterDbRefItem>b__0(Object obj, BsonMapper m)
   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.ToDocument(Type type, Object entity)
   at LiteDB.BsonMapper.ToDocument[T](T entity)
   at LiteDB.LiteCollection`1.Insert(T entity)

**Additional context**
I have seen a similar issue in the past to do with type detection in dotnet core as the types moved from a different dll in normal dotnet to System.Private.CoreLib in dotnet core by default. Int hat case we needed to only match on class namespace and not the source dll.

**Comment by seertenedos** [comment]
sorry my mistake i had an old DbRef registered in the mapper that caused it.
