### ISSUE TITLE
[BUG] Using Query.Or() inside .Find() results in NullReference exception

### ISSUE THREAD

**Issue by JensSchadron** [mbdavid/LiteDB#1527]
**Version**
_Which LiteDB version/OS/.NET framework version are you using. **(REQUIRED)**_
LiteDB build from master (commit 6debdd28dd9822db332a6ffb20f4f2a5bbd58d64)
Windows 10 1909 (build 18363.693)
.NET Core 3.1.102

**Describe the bug**
_A clear and concise description of what the bug is._
Using `Query.Or()` inside `.Find()` results in a NullReference exception.

**Code to Reproduce**
_Write a small snippet to isolate your bug and could be possible to our team test. **(REQUIRED)**_
```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace LiteDB.Sandbox
{
	class Program
	{
		private static DateTime _dateTimeConstraint;
		private static BsonValue _dateTimeConstraintBsonValue;
		private static ILiteCollection<FileMetaBase> _fileMetaCollection;

		static void Main(string[] args)
		{
			var databasePath = "LiteDB.db";
			File.Delete(databasePath);

			var databaseInstance = new LiteDatabase(new ConnectionString(databasePath) {Connection = ConnectionType.Direct});
			_fileMetaCollection = databaseInstance.GetCollection<FileMetaBase>();
			_fileMetaCollection.EnsureIndex(fileMeta => fileMeta.ValidFrom);
			_fileMetaCollection.EnsureIndex(fileMeta => fileMeta.ValidTo);
			_fileMetaCollection.EnsureIndex(fileMeta => fileMeta.ShouldBeShown);

			_fileMetaCollection.Insert(FileMetaGenerator<FileMetaBase>.GenerateList(10)); // executed once per each N value

			databaseInstance.Checkpoint();

			_dateTimeConstraint = DateTime.Now;
			_dateTimeConstraintBsonValue = new BsonValue(_dateTimeConstraint);

			//var metaBases = _fileMetaCollection.Find(BsonExpression.Create("$.ValidFrom>={$date:\"2020-02-29T21:47:03.6160000Z\"}")).ToList();

			// This works
			var metaBases1 = _fileMetaCollection.Find(
					Query.And(
						Query.GTE(nameof(FileMetaBase.ValidFrom), _dateTimeConstraintBsonValue),
						Query.LTE(nameof(FileMetaBase.ValidTo), _dateTimeConstraintBsonValue)))
				.ToList();

			// This, however, doesn't as it throws a NullReference exception
			var metaBases2 = _fileMetaCollection.Find(
					Query.Or(
						Query.GTE(nameof(FileMetaBase.ValidFrom), _dateTimeConstraintBsonValue),
						Query.LTE(nameof(FileMetaBase.ValidTo), _dateTimeConstraintBsonValue)))
				.ToList();
			// But querying like this works just fine again
			// var metaBases2Working = _fileMetaCollection.Find(BsonExpression.Create("$.ValidFrom>={$date:\"2020-02-29T22:26:22.5520000Z\"} OR $.ValidTo<={$date:\"2020-02-29T22:26:22.5520000Z\"}")).ToList();

			// Also throws a NullReference exception. Probably due to the usage of Query.Or()
			var metaBases3 = _fileMetaCollection.Find(Query.And(
					Query.Or(
						Query.GTE(nameof(FileMetaBase.ValidFrom), _dateTimeConstraintBsonValue),
						Query.LTE(nameof(FileMetaBase.ValidTo), _dateTimeConstraintBsonValue)),
					Query.EQ(nameof(FileMetaBase.ShouldBeShown), true)))
				.ToList();
		}
	}

	// Generator and model class borrowed from the LiteDB.Benchmarks project.
	// You can probably ignore everything below this.
	static class FileMetaGenerator<T> where T : FileMetaBase, new()
	{
		private static Random _random;

		private static T Generate()
		{
			var docGuid = Guid.NewGuid();

			var generatedFileMeta = new T
			{
				FileId = docGuid,
				Version = _random.Next(5),
				Title = $"Document-{docGuid}",
				MimeType = "application/pdf",
				IsFavorite = _random.Next(10) >= 9,
				ShouldBeShown = _random.Next(10) >= 7
			};

			if (_random.Next(10) >= 5)
			{
				generatedFileMeta.ValidFrom = DateTimeOffset.Now.AddDays(-20 + _random.Next(40));
				generatedFileMeta.ValidFrom = DateTimeOffset.UtcNow.AddDays(-10 + _random.Next(40));
			}

			return generatedFileMeta;
		}

		public static List<T> GenerateList(int amountToGenerate)
		{
			_random = new Random(0);

			var generatedList = new List<T>();
			for (var i = 0; i < amountToGenerate; i++) generatedList.Add(Generate());

			foreach (var fileMeta in generatedList)
			{
				if (_random.Next(100) <= 1)
				{
					continue;
				}

				fileMeta.ParentId = generatedList[_random.Next(amountToGenerate)].Id;
			}

			return generatedList;
		}
	}

	public class FileMetaBase
	{
		[BsonIgnore]
		public const string BsonIdPropertyKey = "_id";
		[BsonId]
		public virtual string Id => $"{FileId}_{Version}";
		public Guid FileId { get; set; }
		public string ParentId { get; set; }
		public string Title { get; set; }
		public string MimeType { get; set; }
		public int Version { get; set; }
		public DateTimeOffset? ValidFrom { get; set; }
		public DateTimeOffset? ValidTo { get; set; }
		public bool IsFavorite { get; set; }
		public bool ShouldBeShown { get; set; }
		public virtual bool IsValid => ValidFrom == null || ValidFrom <= DateTimeOffset.UtcNow && ValidTo == null || ValidTo > DateTimeOffset.UtcNow;
	}
}
```

**Expected behavior**
_A clear and concise description of what you expected to happen._
The code is expected to return some elements

**Screenshots/Stacktrace**
_If applicable, add screenshots/stacktrace_
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.BsonExpression.ExecuteScalar(IEnumerable`1 source, BsonDocument root, BsonValue current, Collation collation) in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Document\Expression\BsonExpression.cs:line 244
   at LiteDB.BsonExpression.ExecuteScalar(BsonDocument root, Collation collation) in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Document\Expression\BsonExpression.cs:line 224
   at LiteDB.Engine.BasePipe.Filter(IEnumerable`1 source, BsonExpression expr)+MoveNext() in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Engine\Query\Pipeline\BasePipe.cs:line 139
   at LiteDB.Engine.QueryPipe.Select(IEnumerable`1 source, BsonExpression select)+MoveNext() in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Engine\Query\Pipeline\QueryPipe.cs:line 85
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext() in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Engine\Query\QueryExecutor.cs:line 131
   at LiteDB.BsonDataReader..ctor(IEnumerable`1 values, String collection) in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Document\DataReader\BsonDataReader.cs:line 49
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan) in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Engine\Query\QueryExecutor.cs:line 63
   at LiteDB.Engine.QueryExecutor.ExecuteQuery() in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Engine\Query\QueryExecutor.cs:line 43
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query) in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Engine\Engine\Query.cs:line 35
   at LiteDB.LiteQueryable`1.ExecuteReader() in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Client\Database\LiteQueryable.cs:line 238
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext() in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB\Client\Database\LiteQueryable.cs:line 246
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LiteDB.Sandbox.Program.Main(String[] args) in C:\Users\jenss\Documents\Projects\LiteDB\LiteDB.Sandbox\Program.cs:line 42
```

**Additional context**
_Add any other context about the problem here._
I thought it was related to #1521 , but that seems not to be the case.

**Comment by lbnascimento** [comment]
@JensSchadron Fixed.
