### ISSUE TITLE
[QUESTION] Method ToUniversalTime() in DateTime are not supported

### ISSUE THREAD

**Issue by alonstar** [mbdavid/LiteDB#1586]
I filter data by DateTime.Today.ToUniversalTime(), it's working  on 4.1.4 but not 5.0.4. 

Error messaage : Method ToUniversalTime() in DateTime are not supported when convert to BsonExpression (DateTime.Today.ToUniversalTime()).

	db.Query<Order>().Where(p => p.OrderDateUtc > DateTime.Today.ToUniversalTime())

======

	   at LiteDB.LinqExpressionVisitor.VisitMethodCall(MethodCallExpression node)
	   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
	   at LiteDB.LinqExpressionVisitor.VisitAsPredicate(Expression expr, Boolean ensurePredicate)
	   at LiteDB.LinqExpressionVisitor.VisitBinary(BinaryExpression node)
	   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
	   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
	   at LiteDB.LinqExpressionVisitor.VisitLambda[T](Expression`1 node)
	   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
	   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	   at LiteDB.LinqExpressionVisitor.Resolve(Boolean predicate)
	   at LiteDB.BsonMapper.GetExpression[T,K](Expression`1 predicate)
	   at LiteDB.LiteQueryable`1.Where(Expression`1 predicate)

**Comment by lbnascimento** [comment]
@alonstar I'm going add the Linq-to-BsonExpression mapping for `ToUniversalTime()` later. In the meantime, you can just store the value in a variable before using it in the query:

```C#
var todayUtc = DateTime.Today.ToUniversalTime();
var result = col.Find(p => p.OrderDateUtc > todayUtc);
```
