### ISSUE TITLE
[QUESTION] Strange issue records getting damaged

### ISSUE THREAD

**Issue by seertenedos** [mbdavid/LiteDB#1600]
I am hoping someone can point me in the right direction here and then i will raise it as a bug if it is a bug.

Basically my database is having around 90,000 records over 3 tables and about 20 meg of disk space so nothing huge but there are a lot of actions happening and normally in a transaction over the 3 tables.
Everything will be working fine then all of a sudden i can't get records from one of my tables and will start to get "BSON type not supported" errors for anything on that table. I am using the latest master code with the fix for null values in the index. I have pasted the excaption below. 

So far i have been unable to duplicate the triggering condition inside my development environment but i can trigger it when the application is used normally.

```
BSON type not supported

===================================================
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.DatafileLookup.Load(PageAddress rawId)
   at LiteDB.Engine.DatafileLookup.Load(IndexNode node)
   at LiteDB.Engine.BasePipe.<LoadDocument>d__6.MoveNext()
   at LiteDB.Engine.DocumentCacheEnumerable.<GetEnumerator>d__5.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at lambda_method(Closure , IEnumerable`1 , BsonDocument , BsonValue , Collation , BsonDocument )
   at LiteDB.BsonExpression.<Execute>d__55.MoveNext()
   at LiteDB.Engine.QueryPipe.<SelectAll>d__3.MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader..ctor(IEnumerable`1 values, String collection)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery()
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.SqlParser.ParseSelect()
   at LiteDB.SqlParser.Execute()
   at LiteDB.LiteDatabase.Execute(TextReader commandReader, BsonDocument parameters)
   at LiteDB.Studio.MainForm.CreateThread(TaskData task)
```

**Comment by seertenedos** [comment]
sorry i realised I am not on the latest but checkin https://github.com/mbdavid/LiteDB/commit/648fd5c7a1d39864588f05d2528a8a9ab3b70788.

I am going to test with the latest as well

**Comment by seertenedos** [comment]
Latest source also has the issue but i now know a little more. It is not all records that are broken just some of them and specifically ones that have values in a property of type "Dictionary<string, Guid>". Hopeing to be able to have some code to duplicate the issues soon

**Comment by seertenedos** [comment]
so far i still can duplicate the trigger condition in a development environment. Multi rows in a dictionary did not trigger it and i can see other records are fine.

**Comment by seertenedos** [comment]
looks like the database is getting corrupt or damaged so will open a bug
