### ISSUE TITLE
[BUG] Dictionaries in entity models are serialized incorrectly, causing InvalidCastException on deserialization

### ISSUE THREAD

**Issue by bennettn404** [mbdavid/LiteDB#1675]
**Version**
LiteDB: 5.0.7
Microsoft.AspNetCore.App: 2.1.1
Microsoft.NETCore.App: 2.1

**Describe the bug**
Dictionaries always seem to be serialized as Dictionary<string, object>.
Dictionaries with generic types <Object1, Object2> are converted to <string, Object2> via Object1.ToString 
When deserializing from database, InvalidCastException is thrown when converting from string to Object1.

**Code to Reproduce**
A test entity model
```           
namespace DictionaryTest.Models.Database
{
    public class DictTestClass
    {
        public int ID { get; set; }
        public Dictionary<Object1, Object2> ValidObject2ForObject1 { get; set; }
    }

    public class Object1
    {
        public int someProp1 { get; set; }
        public string someProp2 { get; set; }
    }

    public class Object2
    {
        public int someProp3 { get; set; }
        public string someProp4 { get; set; }
    }
}
```
Below is the test case
```
            Dictionary<Object1, Object2> testDict = new Dictionary<Object1, Object2>();

            Object1 object1 = new Object1();
            object1.someProp1 = 4;
            object1.someProp2 = "object1key";
            Object2 object2 = new Object2();
            object2.someProp3 = 8;
            object2.someProp4 = "object1value";

            testDict.Add(object1, object2);

            DictTestClass testDictTestClass = new DictTestClass();
            testDictTestClass.ID = 1;
            testDictTestClass.ValidObject2ForObject1 = testDict;

            dictTestRepo.updateOrAddDictTest(testDictTestClass);
```
The serialized object in the database
```
{
  "_id": 1,
  "ValidObject2ForObject1": 
  {
    "DictionaryTest.Models.Database.Object1": 
    {
      "someProp3": 8,
      "someProp4": "object1value"
    }
  }
}
```
**NOTE:** The key is serialized using the default ToString method for the object. If ToString is overridden, that is used instead.

**Expected behavior**
The dictionary should not be forcefully converted to a Dictionary<String, Object2>, and instead should have the keys be properly serialized.

**Screenshots/Stacktrace**
```
System.InvalidCastException: Invalid cast from 'System.String' to 'DictionaryTest.Models.Database.Object1
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at LiteDB.BsonMapper.DeserializeDictionary(Type K, Type T, IDictionary dict, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
```

**Additional context**
Looking at the LiteDB source, 
BsonMapper.Serialize:
```
        private BsonDocument SerializeDictionary(Type type, IDictionary dict, int depth)
        {
            var o = new BsonDocument();

            foreach (var key in dict.Keys)
            {
                var value = dict[key];
                var skey = key.ToString();

                if (key is DateTime dateKey)
                {
                    skey = dateKey.ToString("o");
                }

                o[skey] = this.Serialize(type, value, depth);
            }

            return o;
        }
```
You can see the key's being forcefully serialized to string.

**Comment by lbnascimento** [comment]
@bennettn404 The LiteDB documentation states that "For `IDictionary<K, T>`, `K` key must be `String` or a simple type (convertible using `Convert.ToString(..)`)". So this is technically not an issue, but a documented limitation.

We may consider ways to improve this part of our serialization, however I'm not sure what could be done (if you have any ideas, please let us know).
