### ISSUE TITLE
[BUG] - CryptographicException creating DB with password

### ISSUE THREAD

**Issue by Chris7918** [mbdavid/LiteDB#1700]
**Version**
LiteDB v5.08 - .NET Framework v4.5

**Describe the bug**
When creating a DB with password, a CryptographicException occurs. If no password is supplied DB is created and data saved.

**Code to Reproduce**
```C#
public void SaveCollection<T>(string collectionName, List<T> items)
{
    if (this.connString != null)
    {
        using (var db = new LiteDatabase(this.connString))
        {
            var collection = db.GetCollection<T>(collectionName);
            collection.InsertBulk(items);
        }
    }

}

private ConnectionString SetConnectionString()
{
    try
    {
        this.connString = new ConnectionString();
        this.connString.Filename = $"{this.dbPath}{this.dbName}.db";
        this.connString.Password = this.dbPassword;
        this.connString.ReadOnly = this.readOnly;
        this.connString.Upgrade = this.updateDB;
        this.connString.InitialSize = 1000;

        return this.connString;
    }
    catch (Exception)
    {
        return null;
    }
}
```

**Expected behavior**
Save collection occurs and DB is encrypted with password.

**Screenshots/Stacktrace**
Test Name:	SaveData
Test FullName:	Component.OfflineData.Tests.LiteDBTests.SaveData
Test Source:	C:\Data\Dev\Component.OfflineData.Tests\LiteDBTests.cs : line 22
Test Outcome:	Failed
Test Duration:	0:00:00.299671

Result StackTrace:
```
at System.Security.Cryptography.CapiSymmetricAlgorithm.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at LiteDB.Engine.AesStream.Read(Byte[] array, Int32 offset, Int32 count)
   at LiteDB.Engine.DiskService.<ReadFull>d__22.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at Component.OfflineData.DB.Services.DatabaseService.SaveCollection[T](String collectionName, List`1 items) in C:\Data\Dev\Component.OfflineData.DB\Services\DatabaseService.cs:line 92
   at Component.OfflineData.Tests.LiteDBTests.SaveData() in C:\Data\Dev\Component.OfflineData.Tests\LiteDBTests.cs:line 36
Result Message:	
Test methodComponent.OfflineData.Tests.LiteDBTests.SaveData threw exception: 
System.Security.Cryptography.CryptographicException: The input data is not a complete block.
```

**Comment by lbnascimento** [comment]
@Chris7918 I'm trying to work out exactly why this is happening, but a simple workaround would be to remove the `InitialSize` option.

**Comment by Chris7918** [comment]
Hi,

I've stripped my connection string back to just filename and password, and I'm still getting the same exception, but now in a different place.

private ConnectionString SetConnectionString()
        {
            try
            {
                this.connString = new ConnectionString();
                this.connString.Filename = $"{this.dbPath}{this.dbName}.db";
                this.connString.Password = this.dbPassword;

                return this.connString;
            }
            catch (Exception)
            {
                return null;
            }
        }



Test Name:	SaveData
Test FullName:	Component.OfflineData.Tests.LiteDBTests.SaveData
Test Source:	C:\Data\Dev\Component.OfflineData.Tests\LiteDBTests.cs : line 22
Test Outcome:	Failed
Test Duration:	0:00:00.248159

Result StackTrace:	
at System.Security.Cryptography.CapiSymmetricAlgorithm.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at LiteDB.Engine.AesStream.Read(Byte[] array, Int32 offset, Int32 count)
   at LiteDB.Engine.DiskService.<ReadFull>d__22.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at Component.OfflineData.DB.Services.DatabaseService.SaveCollection[T](String collectionName, List`1 items) in C:\Data\Dev\Component.OfflineData.DB\Services\DatabaseService.cs:line 92
   at Component.OfflineData.Tests.LiteDBTests.SaveData() in C:\Data\Dev\Component.OfflineData.Tests\LiteDBTests.cs:line 36
Result Message:	
Test method Component.OfflineData.Tests.LiteDBTests.SaveData threw exception: 
System.Security.Cryptography.CryptographicException: The input data is not a complete block.

**Comment by lbnascimento** [comment]
@Chris7918 Could you send me your datafile?

**Comment by Chris7918** [comment]
Here's the db file.

Thanks,
Chris

[test.zip](https://github.com/mbdavid/LiteDB/files/4716289/test.zip)

**Comment by lbnascimento** [comment]
@Chris7918 I need to know the password too

**Comment by Chris7918** [comment]
Password is "7XUK#KLM3JHU(DX<7XUK#KLM3JHU(DX<"

**Comment by lbnascimento** [comment]
@Chris7918 You're trying to read the encrypted file you created with `InitialSize`, which is now an invalid file due to its size. Just create another file without the `InitialSize` option and it should work out fine. A validation was commited to our master to prevent `InitialSize` from being used with encrypted datafiles.

**Comment by Chris7918** [comment]
That worked, thanks for the support.
