### ISSUE TITLE
[BUG] 'System.IO.IOException: Sharing violation on path' on Android

### ISSUE THREAD

**Issue by mikhail-khalizev** [mbdavid/LiteDB#1709]
**Version**
5.0.8

**Describe the bug**
When application runs on Android (Xamarin), exception `System.IO.IOException: Sharing violation on path` always occurs in `LiteDatabase` constructor.

**Code to Reproduce**
```
var cs = new ConnectionString();
cs.Connection = ConnectionType.Direct;
cs.Upgrade = true;
cs.Filename = Path.Combine(fileSystem.AppDataDirectory, "app.db");
App = new LiteDatabase(cs); // throw Exception.
```

**Expected behavior**
No exceptions.

**Screenshots/Stacktrace**
```
android.runtime.JavaProxyThrowable: System.IO.IOException: Sharing violation on path /data/user/0/ru.awatem.iot.client.android/files/app.db
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001b7] in <583dbbe0ab8e45ae857c9e7b80dd9b6c>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <583dbbe0ab8e45ae857c9e7b80dd9b6c>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
  at LiteDB.Engine.FileStreamFactory.GetStream (System.Boolean canWrite, System.Boolean sequencial) [0x0001e] in <7b8c154640e6442cbc93e4644732d128>:0 
  at LiteDB.Engine.StreamPool+<>c__DisplayClass3_0.<.ctor>b__0 () [0x00000] in <7b8c154640e6442cbc93e4644732d128>:0 
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <583dbbe0ab8e45ae857c9e7b80dd9b6c>:0 
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <583dbbe0ab8e45ae857c9e7b80dd9b6c>:0 
  at System.Lazy`1[T].CreateValue () [0x00074] in <583dbbe0ab8e45ae857c9e7b80dd9b6c>:0 
  at System.Lazy`1[T].get_Value () [0x0000a] in <583dbbe0ab8e45ae857c9e7b80dd9b6c>:0 
  at LiteDB.Engine.StreamPool.get_Writer () [0x00000] in <7b8c154640e6442cbc93e4644732d128>:0 
  at LiteDB.Engine.DiskService..ctor (LiteDB.Engine.EngineSettings settings, System.Int32[] memorySegmentSizes) [0x0009a] in <7b8c154640e6442cbc93e4644732d128>:0 
  at LiteDB.Engine.LiteEngine..ctor (LiteDB.Engine.EngineSettings settings) [0x00173] in <7b8c154640e6442cbc93e4644732d128>:0 
  at LiteDB.ConnectionString.CreateEngine () [0x0004a] in <7b8c154640e6442cbc93e4644732d128>:0 
  at LiteDB.LiteDatabase..ctor (LiteDB.ConnectionString connectionString, LiteDB.BsonMapper mapper) [0x0002e] in <7b8c154640e6442cbc93e4644732d128>:0 
```

**Additional context**
I did a little investigation and maybe found a reason. The exception is thrown when several FileStream are created on the same file without Dispose the previous one.

How I see, when LiteDatabase constructed, it twice accesses to database file:

```
   at LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
   at LiteDB.Engine.StreamPool.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at LiteDB.Engine.StreamPool.get_Writer()
   at LiteDB.Engine.DiskService..ctor(EngineSettings settings, Int32[] memorySegmentSizes)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
```

```
   at LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
   at LiteDB.Engine.StreamPool.Rent()
   at LiteDB.Engine.DiskService.ReadFull(FileOrigin origin)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at Awatem.IoT.Client.Backend.Database.DbContext..ctor(IFileSystem fileSystem)
```

Which leads to exception.

**Comment by mikhail-khalizev** [comment]
Video of exception from google play: https://yadi.sk/d/TXI4ZGcOCVu_nA

**Comment by mikhail-khalizev** [comment]
Sorry, seems it's my error. For some reason I initialize Database twice.
