### ISSUE TITLE
[QUESTION] Querying DateTime throws exception after updating to 5.0.9

### ISSUE THREAD

**Issue by mregni** [mbdavid/LiteDB#1787]
I just updated to LiteDB 5.0.9 (from 5.0.8) and I'm getting a strange exception
```
System.InvalidCastException : Unable to cast object of type 'System.DateTime' to type 'System.Nullable`1[System.DateTimeOffset]'.
   at lambda_method(Closure , Object , Object )
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

My model has 3 nullable DateTimeOffsets but seems to work in 5.0.8. Any idea what could make it fail. I read in the release notes about custom serializers. But not sure if it has anything to do with my problem.

**Comment by lbnascimento** [comment]
@mregni This issue has been fixed in the master and its fix will be present in the next incremental release.
