### ISSUE TITLE
[QUESTION] Calling ToArray() causes query to fail with Null Object Reference error

### ISSUE THREAD

**Issue by captmomo** [mbdavid/LiteDB#1789]
```

            var tester = userGenerator.Generate();

            var testerId = context
                .LiteDatabase
                .GetCollection<User>()
                .Insert(tester);


            messages.ForEach((item) => item.User = context
            .LiteDatabase
            .GetCollection<User>()
            .FindById(testerId));

            context.LiteDatabase
                .GetCollection<LogMessage>()
                .InsertBulk(messages);
//this is ok
            var results = context
                .LiteDatabase
                .GetCollection<LogMessage>()
                .Include(x => x.User)
                .Find(Query.EQ("$.User.$id", 102));
//this fails
            var test5 = context
                .LiteDatabase
                .GetCollection<LogMessage>()
                .Find(Query.EQ("$.User.$id", 102))
                .ToArray();

```

Exception

```
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.<>c__DisplayClass51_0.<RegisterDbRefItem>b__1(BsonValue bson, BsonMapper m)
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at liteDbSample.Program.<Main>d__1.MoveNext() in C:\azurerepos\Arcstone Internal - Development\serilog.sinks.webapi\src\sample\liteDb\Program.cs:line 107
```

**Comment by lbnascimento** [comment]
@captmomo I believe you're using `DbRef` for the property `User` in `LogMessage`. In that case, you should always run `Include`, unless you don't need to retrieve that field in a particular query (you'll have better performance in this case).

To make it clearer:
* `DbRef` tells LiteDB to store this sub-object in a separate collection (by default, LiteDB would store it as an embedded document in the same collection);
* `Include` tells LiteDB to resolve the reference upon retrieval (so you can avoid using it if you know you won't use the sub-object in a particular query).
