### ISSUE TITLE
[BUG] System.UnauthorizedAccessException still happening

### ISSUE THREAD

**Issue by mikehachen** [mbdavid/LiteDB#1798]
**Version**
5.0.9 / Windows Server 2012 / .NET Framework 4.7.2

**Describe the bug**
While developping everything works as expected. However as soon as I install the application as a Windows Service I get a System.UnauthorizedAccessException when the application tries to open the database. It can't be a problem with security or access rights because the same application / windows service can open xml files in the very same directory without any problems.

**Code to Reproduce**
```
private ConnectionString GetConnectionString()
    {
      var connectionStringBuilder = new ConnectionString {Upgrade = true, Filename = Path.Combine(_settingsPath, _databaseName)};
      return connectionStringBuilder;
    }

    public List<ScriptHandlerSettings> GetScriptHandlerSettings()
    {
      using (var db = new LiteDatabase(GetConnectionString()))
      {
        var configurations = db.GetCollection<ScriptHandlerSettings>(ScriptHandlerSettingCollectionName);
        return configurations.Query().OrderBy(p => p.Id).ToList();
      }
    }
```

**Expected behavior**
LiteDb should be able to open the database without any exception.

**Screenshots/Stacktrace**
```
System.UnauthorizedAccessException: Access to the path 'D:\ProIT Quartz Scheduler Installer (DEV)\SettingsFiles' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LiteDB.Engine.DiskService..ctor(EngineSettings settings, Int32[] memorySegmentSizes)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at ProIT.QuartzScheduler.PhpScriptHandler.Services.ScriptHandlerSettingDatabaseService.GetScriptHandlerSettings()
   at ProIT.QuartzScheduler.PhpScriptHandler.Services.PhpScriptExecutor.<ExecuteAllScripts>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProIT.QuartzScheduler.PhpScriptHandler.Jobs.PhpScriptHandlerJob.<Execute>d__3.MoveNext()
```

**Additional context**
The application uses Quartz.NET to run multiple background jobs. However each job can only run one at a time (Attribute `[DisallowConcurrentExecution]` is used to prevent concurrent running jobs)

**Comment by lbnascimento** [comment]
@mikehachen I believe there's something wrong with your `Path.Combine(...)` call, because the path `D:\ProIT Quartz Scheduler Installer (DEV)\SettingsFiles` seems to be a directory.

**Comment by mikehachen** [comment]
Hello
It's so embarrassing... In Switzerland there is a saying: to not see the forest for the trees. I checked the code at least 100 times but overlooked the obvious. And then I also found an entry in the Issue Tracker about a similar problem... Sorry, everything works wonderfully!

**Comment by lbnascimento** [comment]
@mikehachen I don't blame you, I had no idea that `File.Open(...)` threw a `UnauthorizedAccessException` if it tries to open the path to a folder. The message `Access to the path [...] is denied` is also very misleading.
