### ISSUE TITLE
[BUG] Rebuild database fails (IndexOutOfRangeException)

### ISSUE THREAD

**Issue by meeety** [mbdavid/LiteDB#1932]
**Version**
5.0.10

**Describe the bug**
Rebuild fails with unhandled exception "IndexOutOfRangeException" at LiteDB.Engine.DataPage.GetBlocks()+MoveNext().

**Code to Reproduce**
There is no code to reproduce. Just Rebuild the attached database to get the error.

**Expected behavior**
Database rebuild without any issue.

**Screenshots/Stacktrace**
`Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LiteDB.Engine.DataPage.GetBlocks()+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at LiteDB.Engine.FileReaderV8.GetDocuments(String collection)+MoveNext()
   at LiteDB.Engine.LiteEngine.RebuildContent(IFileReader reader)
   at LiteDB.Engine.LiteEngine.Rebuild(RebuildOptions options)
   at LiteDB.LiteDatabase.Rebuild(RebuildOptions options)`

**Additional context**
I would like to share with you the database of 2 GB size for analysis. Pls advice how to share with you.

Thank you a lot!
With best regards,
Vlastimil

**Comment by arty1901** [comment]
Can you send to me a link (e.g. google drive) to your db to reproduce bug?

**Comment by meeety** [comment]
Since I cannot find the corrupted database now, I close this issue. Thank you.
