### ISSUE TITLE
[QUESTION] How to use LiteDB with ASP.NET Core API

### ISSUE THREAD

**Issue by Crashdummyy** [mbdavid/LiteDB#1962]
Hey there,

I want to use the LiteDB in an ASP.NET Core Project.
I cant however figure out how to prevent the error:  

***The read lock is being released without being held.***

Ioc
```csharp
services.AddSingleton(_ => new LiteDatabase(connectionString));          
services.AddSingleton<IGameRepository, Data.NoSql.Repositories.GameRepository>()
        .AddSingleton<IDefaultArgsRepository, Data.NoSql.Repositories.DefaultArgsRepository>();
```

Registering as Transient or Scoped didn't work either.

Those repos inherit one base Repository:
```csharp
    public class Repository<T> : IRepository<T, int>
        where T : class, IEntity<int>
    {
        protected readonly LiteDatabase Context;
        protected ILiteCollection<T> Collection;

        /// <inheritdoc />
        public T FirstOrDefault(int id) => Collection.FindById(id);

        /// <inheritdoc />
        public T FirstOrDefault(Expression<Func<T, bool>> predicate) => Collection.FindOne(predicate);

        /// <inheritdoc />
        public IEnumerable<T> Where(Expression<Func<T, bool>> predicate) => Collection.Find(predicate);

        /// <inheritdoc />
        public IEnumerable<T> All() => this.Collection.FindAll();

        /// <inheritdoc />
        public T Add(T entity)
        {
            Collection.Insert(entity);
            return entity;
        }

        public Repository(LiteDatabase context)
        {
            this.Context = context;
            this.Collection = this.Context.GetCollection<T>(typeof(T).Name);
        }

```

At first everything appeared to work fine.
Whenever I try to access the database from another location than my localhost, I get slapped with an Exception:

```csharp
Exception: 
System.Threading.SynchronizationLockException: The read lock is being released without being held.
   at System.Threading.ReaderWriterLockSlim.ExitReadLock()
   at LiteDB.Engine.LockService.ExitTransaction()
   at LiteDB.Engine.TransactionMonitor.ReleaseTransaction(TransactionService transaction)
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.<>m__Finally1()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader.Read()
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore[TValue](Stream utf8Json, TValue value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Any help on this matter is appreciated :)

**Comment by Crashdummyy** [comment]
Resigning...

```csharp
        protected readonly Func<ILiteDatabase> CreateConnection;

        /// <inheritdoc />
        public T FirstOrDefault(int id)
        {
            using var connection = CreateConnection();
            var result = CollectionFor(connection).FindById(id);
            return result;
        }

        /// <inheritdoc />
        public T FirstOrDefault(Expression<Func<T, bool>> predicate)
        {
            using var connection = CreateConnection();
            var result = CollectionFor(connection).FindOne(predicate);
            return result;
        }

        /// <inheritdoc />
        public IEnumerable<T> Where(Expression<Func<T, bool>> predicate)
        {
            using var connection = CreateConnection();
            var result = CollectionFor(connection).Find(predicate).ToList();
            return result;
        }

        /// <inheritdoc />
        public IEnumerable<T> All()
        {
            using var connection = CreateConnection();
            var result = CollectionFor(connection).FindAll().ToList();
            return result;
        }
```
