### ISSUE TITLE
ISSUE:  Can't insert JObjects into the Database

### ISSUE THREAD

**Issue by mikeostacie** [mbdavid/LiteDB#197]
I have a class where one of the Properties is a JObject.  If the JObject is anything but null I get the following error:

Index was outside the bounds of the array.

   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Object obj)
   at LiteDB.BsonMapper.ToDocument(Object entity)
   at LiteDB.LiteCollection`1.Insert(T document)

Is storing a JObject not permitted?  

Thanks!

**Comment by mbdavid** [comment]
Hi @mikeostacie, JObject must be register as a custom type to BsonMapper serialize/deserialize. If you are using v2.0rc use `OnModelCreating(BsonMapper m) { m.RegisterType<JObject>( ... )`

**Comment by mikeostacie** [comment]
Thanks so much!  Awesome work by the way!
