### ISSUE TITLE
[QUESTION] Error when mapping SOME enums. But there's no logic to when.

### ISSUE THREAD

**Issue by mifriis** [mbdavid/LiteDB#2015]
Hi,
I'm getting some weird results when using Enums in LiteDB. From what i can gather it's supported out of the box in LiteDB5 and onwards. I have created this test class to show the problem:

This is dotnetcore3.1
```C#
using Xunit;
using System;
using LiteDB;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;

namespace MyTests.LiteDB.Tests.Integration
{
   public enum SubscriptionStatus
    {
        Requested,
        Pending,
        Denied,
        Approved
    }

    public enum TestEnum
    {
        StateOne,
        StateTwo,
        StateThree,
        Approved
    }

    public class TopicSubscription
    {
        public TopicSubscription(string subscriptionName, SubscriptionStatus status) {
            SubscriptionName = subscriptionName;
            SubscriptionStatus = status;
        }

        public string SubscriptionName { get; }

        public SubscriptionStatus SubscriptionStatus { get; }
    }

    public class TestClass
    {
        public TestClass(string name, TestEnum state) {
            Name = name;
            State = state;
        }

        public string Name { get; }

        public TestEnum State { get; }
    }

    public class LiteDB_Should
    {
        private const string _connectionString = "myDB.db";
        private IConfiguration _configuration;
        
        public LiteDB_Should()
        {
            var config = new Dictionary<string,string> {
                {"LiteDBConnectionString", _connectionString}
            };

            IConfiguration configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(config)
                .Build();

            _configuration = configuration;
        }

        [Fact]
        public void Create_Testdata_Persisted_in_DB()
        {
            //Arrange
            var name = Guid.NewGuid().ToString();
            var testClass = new TestClass(name,TestEnum.StateOne);
            
            using (var db = new LiteDatabase(_connectionString))
            {
                var collection = db.GetCollection<TestClass>("testdata");
                collection.EnsureIndex(x => x.Name, true);
                collection.Insert(testClass);
            }
            //Act


            //Assert
            using (var db = new LiteDatabase(_connectionString)) 
            {
                var col = db.GetCollection<TestClass>("testdata");
                var testClasses = col
                    .Query()
                    .Where(x => x.Name == name)
                    .ToList();

                Assert.Single<TestClass>(testClasses);
                Assert.Equal(testClasses[0].Name, name);
            }
        }

         [Fact]
        public void Create_Subscriptiondata_Persisted_in_DB()
        {
            //Arrange
            var name = Guid.NewGuid().ToString();
            var testClass = new TopicSubscription(name,SubscriptionStatus.Approved);
            
            using (var db = new LiteDatabase(_connectionString))
            {
                var collection = db.GetCollection<TopicSubscription>("subscriptions");
                collection.EnsureIndex(x => x.SubscriptionName, true);
                collection.Insert(testClass);
            }
            //Act


            //Assert
            using (var db = new LiteDatabase(_connectionString)) 
            {
                var col = db.GetCollection<TopicSubscription>("subscriptions");
                var testClasses = col
                    .Query()
                    .Where(x => x.SubscriptionName == name)
                    .ToList();

                Assert.Single<TopicSubscription>(testClasses);
                Assert.Equal(testClasses[0].SubscriptionName, name);
            }
        }

        public void Dispose()
        {
            var db = new LiteDatabase(_connectionString);
            db.DropCollection("testclasses");
            db.DropCollection("subscriptions");
        }
    }
}
```

When the two test facts are executed, the one based around serialization of "TestClass" will pass, but the one about "TopicSubscription" will fail with this error:

```TERMINAL
MyTests.LiteDB.Tests.Integration.LiteDB_Should.Create_Subscriptiondata_Persisted_in_DB:
    Outcome: Failed
    Error Message:
    System.ArgumentNullException : Value cannot be null. (Parameter 'value')
    Stack Trace:
       at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at lambda_method(Closure , BsonDocument )
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LiteDB.LiteQueryable`1.ToList()
   at MyTests.LiteDB.Tests.Integration.LiteDB_Should.Create_Subscriptiondata_Persisted_in_DB() in LiteDBTest.cs:line 117
```

I am pretty baffled and have stared at what could be the issue. Maybe it's obvious with a fresh pair of eyes, but the approach looks to me like the same.

This is line 117:

```c#
var testClasses = col
                    .Query()
                    .Where(x => x.SubscriptionName == name)
                    .ToList();
```

Looking at the raw data from LiteDB Studio nothing seems wrong with the data:
![image](https://user-images.githubusercontent.com/1443594/121536927-c7290900-ca03-11eb-8a5c-386742758434.png)
![image](https://user-images.githubusercontent.com/1443594/121537000-d3ad6180-ca03-11eb-9135-cf953558df9a.png)

Do you have any clue what could be wrong here? The class above should be copyable into any dotnetcore c# project with xunit and litedb installed.

**Comment by mifriis** [comment]
I figured this one out! When using constructors like this:

```C#
 public class TopicSubscription
    {
        public TopicSubscription(string subscriptionName, SubscriptionStatus status) {
            SubscriptionName = subscriptionName;
            SubscriptionStatus = status;
        }

        public string SubscriptionName { get; }

        public SubscriptionStatus SubscriptionStatus { get; }
    }
```

Some string matching magic is involved. So `SubscriptionStatus status` needs to be `SubscriptionStatus subscriptionStatus` the the deserializer to know what to insert there.

Fixed version:

```C#
 public class TopicSubscription
    {
        public TopicSubscription(string subscriptionName, SubscriptionStatus subscriptionStatus) {
            SubscriptionName = subscriptionName;
            SubscriptionStatus = status;
        }

        public string SubscriptionName { get; }

        public SubscriptionStatus SubscriptionStatus { get; }
    }
```
