### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by superahoy** [mbdavid/LiteDB#2298]
**Version**
LiteDB 5.0.16 / .NET 7

**Describe the bug**
I have defined a custom CTor method and registered it for a class. I see the custom method called and the expected object is rebuilt and returned by the MassRangeBuilder method. LiteDB is then giving me an InvalidCastException, as if it is trying to either set a property or look for another constructor and is not able to locate one.

**Code to Reproduce**

```csharp
using LiteDB;
using System.Text.Json;

public struct Mass
{
	public enum Units { Pound, Kilogram }
	public Mass(double value, Units unit) { Value = value; Unit = unit; }
	public double Value { get; init; }
	public Units Unit { get; init; }
}

public class QuantityRange<T>
{
	public QuantityRange(double min, double max, Enum unit) { Min = min; Max = max; Unit = unit; }
	public double Min { get; init ;}
	public double Max { get; init ;}
	public Enum Unit { get; init ;}
}

public class Program
{
	public static QuantityRange<Mass> MassRangeBuilder(BsonDocument document)
	{
		var doc = JsonDocument.Parse(document.ToString()).RootElement;
		var min = doc.GetProperty(nameof(QuantityRange<Mass>.Min)).GetDouble();
		var max = doc.GetProperty(nameof(QuantityRange<Mass>.Max)).GetDouble();
		var unit = Enum.Parse<Mass.Units>(doc.GetProperty(nameof(QuantityRange<Mass>.Unit)).GetString());

		var restored = new QuantityRange<Mass>(min, max, unit);
		return restored;
	}

	public static void Main(string[] args)
	{
		BsonMapper.Global.Entity<QuantityRange<Mass>>().Ctor(MassRangeBuilder);
		var range = new QuantityRange<Mass>(100, 500, Mass.Units.Pound);
		var filename = "Demo.DB";
		var DB = new LiteDatabase(filename);
		var collection = DB.GetCollection<QuantityRange<Mass>>("DEMO");
		collection.Insert(range);
		var restored = collection.FindAll().First();
	}
}
```

**Expected behavior**
I expect restored to be a QuantityRange<Mass> object with Min=100, Max=500, Unit=Mass.Unit.Pound. I would expect, based on registering a custom constructor, that LiteDB would call my custom constructor and rely on it to assign properties / restore state.

**Screenshots/Stacktrace**

```csharp
System.InvalidCastException
HResult=0x80004002
Message=Unable to cast object of type 'System.String' to type 'System.Enum'.
Source=LiteDB
StackTrace:
at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
at Program.Main(String[] args) in C:\Users\johns\source\repos\LiteDBBug\LiteDBBug\Program.cs:line 41
```

**Additional context**

Based on my reading of the code, I believe the fix for this bug is in the BsonMapper Deserialize method, around line 197. My assumption is that if a client has registered a custom constructor which accepts the BsonDocument, that constructor method is responsible for deserializing the object. This would support the above workflow and eliminate a potential redundant deserialization of the object, 

I locally made 3 changes to support my workflow and keep all the tests passing

- I updated EntityMapper to have the following new property

```csharp
/// <summary>
/// Flag indicating CreateInstance was defined by a CTor
/// </summary>
internal bool CTor { get; set; } = false;
```

- I updated EntityBuilder as follows

```csharp
/// <summary>
/// Define which property is your document id (primary key). Define if this property supports auto-id
/// </summary>
public EntityBuilder<T> Ctor(Func<BsonDocument, T> createInstance)
{
	_entity.CTor = true; // flag _entity as having a customer CTor
	_entity.CreateInstance = v => createInstance(v);

	return this;
}
```

- I updated BsonMapper Deserialize as follows

```csharp
var entity = this.GetEntityMapper(type);

if (entity.CTor)
{
	return entity.CreateInstance(doc);
}

// initialize CreateInstance
if (entity.CreateInstance == null)

```

**Comment by pjy612** [comment]
maybe you need use
```
BsonMapper.Global.RegisterType
```

**Comment by JKamsker** [comment]
As @pjy612 said, its not a bug. Here is the test: https://github.com/mbdavid/LiteDB/commit/4e20fa86040a28c39206d5033924fbc5676d9131
