### ISSUE TITLE
Exception running example

### ISSUE THREAD

**Issue by nmfpacheco** [mbdavid/LiteDB#252]
Hello all, 
Im facing some troubles runnig your simple example, when I reach the foreach loop
Can you help me please?

      using (var db = new LiteDatabase(@"C:\Temp\MyData.db")) {
        // Get a collection (or create, if doesn't exist)
        var col = db.GetCollection<Customer>("customers");

        // Create your new customer instance
        var customer = new Customer
          {
          Name = "John Doe",
          Phones = new string[] { "8000-0000", "9000-0000" },
          IsActive = true
          };

        // Insert new customer document (Id will be auto-incremented)
        col.Insert(customer);

        // Update a document inside a collection
        customer.Name = "Joana Doe";

        col.Update(customer);

        // Index document using document Name property
        col.EnsureIndex(x => x.Name);

        // Use LINQ to query documents
        var results = col.Find(x => x.Name.StartsWith("Jo"));

        foreach (Customer item in results) {

          }

Exception:

LiteDB.LiteException was unhandled
  ErrorCode=202
  HResult=-2146233088
  Message=Failed to create instance for type 'LiteDBTestConsole.Program+Customer' from assembly 'LiteDBTestConsole.Program+Customer, LiteDBTestConsole, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Checks if the class has a public constructor with no parameters
  Source=LiteDB
  StackTrace:
       em LiteDB.Reflection.CreateInstance(Type type)
       em LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
       em LiteDB.BsonMapper.ToObject(Type type, BsonDocument doc)
       em LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
       em LiteDB.LiteCollection`1.<Find>d__34.MoveNext()
       em LiteDBTestConsole.Program.Main(String[] args)
       em System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       em System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       em Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       em System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by mbdavid** [comment]
Hi @nmfpacheco, is you Customer class a public class (no inner class) with a public constructor with no parameter?

**Comment by nmfpacheco** [comment]
Hi @mbdavid , 
You are right. Customer class was a inner class.... It is solved now, Thanks!!!

**Comment by jotalanusse** [comment]
I hate to bump old issues, but i just can't make this work...
```java
public class Audio
    {
        public Guid Id { get; }
        public string Path { get; }

        public Audio(Guid id, string path)
        {
            Id = id;
            Path = path;
        }
    }

public class Sound
    {
        public Guid Id { get; }
        [BsonField("audio")]
        [BsonRef("audio")]
        public Audio Audio { get; set; }

        public Sound(Guid id, Audio audio)
        {
            Id = id;
            Audio = audio;
        }
    }

ILiteCollection<Sound> soundCollection = db.GetCollection<Sound>("sound");

soundCollection.Insert(new Sound(Guid.NewGuid(), new Audio(Guid.NewGuid(), "path1")));
soundCollection.Insert(new Sound(Guid.NewGuid(), new Audio(Guid.NewGuid(), "path2")));

List<Sound> allSounds = new List<Sound>();
allSounds.AddRange(soundCollection.FindAll().ToList());
```

Exception:

```
Prism.Ioc.ContainerResolutionException
  HResult=0x80131500
  Message=An unexpected error occurred while resolving 'SoundMod.ViewModels.MainWindowViewModel'
  Source=Prism.Unity.Wpf
  StackTrace:
   at Prism.Unity.UnityContainerExtension.Resolve(Type type, ValueTuple`2[] parameters)
   at Prism.Unity.UnityContainerExtension.Resolve(Type type)
   at Prism.PrismInitializationExtensions.<>c.<ConfigureViewModelLocator>b__0_0(Object view, Type type)
   at Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged(Object view, Action`2 setDataContextCallback)
   at Prism.Mvvm.ViewModelLocator.AutoWireViewModelChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Prism.Mvvm.ViewModelLocator.SetAutoWireViewModel(DependencyObject obj, Nullable`1 value)
   at Prism.Common.MvvmHelpers.AutowireViewModel(Object viewOrViewModel)
   at Prism.PrismApplicationBase.Initialize()
   at Prism.PrismApplicationBase.InitializeInternal()
   at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at SoundMod.App.Main()

  This exception was originally thrown at this call stack:
    System.Linq.Expressions.Expression.New(System.Type)
    LiteDB.Reflection.CreateClass(System.Type)
    LiteDB.Reflection.CreateInstance(System.Type)

Inner Exception 1:
ResolutionFailedException: Resolution failed with error: Exception has been thrown by the target of an invocation.

For more detailed information run Unity in debug mode: new UnityContainer().AddExtension(new Diagnostic())

Inner Exception 2:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 3:
LiteException: Failed to create instance for type 'SoundMod.Sound' from assembly 'SoundMod.Sound, SoundMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Checks if the class has a public constructor with no parameters.

Inner Exception 4:
ArgumentException: Type 'SoundMod.Sound' does not have a default constructor (Parameter 'type')
```

I also tried using `[BsonCtor]` on the Sound constructor but I really don't know what might be causing this error. Any help is really appreciated!
