### ISSUE TITLE
[BUG] NullReferenceException while accessing database from multiple threads

### ISSUE THREAD

**Issue by vonzshik** [mbdavid/LiteDB#2563]
**Version**
LiteDB 5.0.21, Windows 10, .NET 9

**Describe the bug**
While accessing LiteDB via `GetCollection` it might throw `NullReferenceException` due to concurrent access from multiple threads. The repro below takes about 4-5 minutes for it to throw (on my machine).

**Code to Reproduce**

```csharp
using LiteDB;

while (true)
{
    var mapper = new BsonMapper();
    using var db = new LiteDatabase("test.db", mapper);
    var tasks = new List<Task>();

    var barrier = new Barrier(20);
    
    tasks.Add(Task.Run(() => Test<C1>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C2>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C3>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C4>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C5>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C6>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C7>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C8>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C9>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C10>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C11>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C12>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C13>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C14>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C15>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C16>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C17>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C18>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C19>(db, barrier)));
    tasks.Add(Task.Run(() => Test<C20>(db, barrier)));

    await Task.WhenAll(tasks);
}

static void Test<T>(LiteDatabase db, Barrier barrier)
{
    barrier.SignalAndWait();
    db.GetCollection<T>();
    db.GetCollection<T>();
}

public class C1
{
    public int ID { get; set; }
}

public class C2
{
    public int ID { get; set; }
}

public class C3
{
    public int ID { get; set; }
}

public class C4
{
    public int ID { get; set; }
}

public class C5
{
    public int ID { get; set; }
}

public class C6
{
    public int ID { get; set; }
}

public class C7
{
    public int ID { get; set; }
}

public class C8
{
    public int ID { get; set; }
}

public class C9
{
    public int ID { get; set; }
}

public class C10
{
    public int ID { get; set; }
}

public class C11
{
    public int ID { get; set; }
}

public class C12
{
    public int ID { get; set; }
}

public class C13
{
    public int ID { get; set; }
}

public class C14
{
    public int ID { get; set; }
}

public class C15
{
    public int ID { get; set; }
}

public class C16
{
    public int ID { get; set; }
}

public class C17
{
    public int ID { get; set; }
}

public class C18
{
    public int ID { get; set; }
}

public class C19
{
    public int ID { get; set; }
}

public class C20
{
    public int ID { get; set; }
}
```

**Expected behavior**
LiteDB shouldn't throw NRE.

**Screenshots/Stacktrace**
```
C:/reps/LiteDBConcurrentAccessBug/LiteDBConcurrentAccessBug/bin/Release/net9.0/LiteDBConcurrentAccessBug.exe
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.                                                                
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)                                                                                                        
   at LiteDB.BsonMapper.GetEntityMapper(Type type)                                                                                                                       
   at LiteDB.LiteCollection`1..ctor(String name, BsonAutoId autoId, ILiteEngine engine, BsonMapper mapper)                                                               
   at Program.<<Main>$>g__Test|0_0[T](LiteDatabase db, Barrier barrier) in C:\reps\LiteDBConcurrentAccessBug\LiteDBConcurrentAccessBug\Program.cs:line 37                
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---                                                                                                                        
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in C:\reps\LiteDBConcurrentAccessBug\LiteDBConcurrentAccessBug\Program.cs:line 32
   at Program.<Main>(String[] args)
```

**Additional context**
This is happening because `_entities` in `BsonMapper` is accessed without a lock, and `Dictionary` doesn't support concurrent usage (in this case reading and writing together).

https://github.com/mbdavid/LiteDB/blob/d083dd09dd2bf7dd56a2743b1c530812b52499cc/LiteDB/Client/Mapper/BsonMapper.cs#L245-L248

**Comment by JKamsker** [comment]
Hey, thanks for that! can you verify this error doesn't happen with condic?

**Comment by vonzshik** [comment]
> Hey, thanks for that! can you verify this error doesn't happen with condic?

I certainly can try, the only problem is that the fact that it's going to run for an hour or so doesn't confirm that there is no issue anymore :(
Even the repro above is quite unstable, I've run it multiple times and has only been able to repro like once or twice.

**Comment by JKamsker** [comment]
@vonzshik With this code the error reproduces within a second:

https://gist.github.com/JKamsker/8c3fe9dd15f61c70abad67dbcc0e788b

**Comment by vonzshik** [comment]
@JKamsker thank you, that repro is indeed much more stable.
So, I replaced the `_entities`'s type from `Dictionary` to `ConcurrentDictionary` and with your repro it didn't fail for the last 5 minutes.

**Comment by JKamsker** [comment]
Sorry, i cant reproduce the issue on master (https://github.com/mbdavid/LiteDB/commit/d083dd09dd2bf7dd56a2743b1c530812b52499cc) do you have an idea why?

**Comment by vonzshik** [comment]
My guess, because `_entities[type]` is assigned very close to the end of the method and the threads we use in repro are started simultaneously, this makes it so every single thread manages to access `_entities` before getting stuck on a lock just before the write happens. That's why this issue is so problematic, any changes in the code/load/version of .NET may or may not result in some kind of exception.

**Comment by JKamsker** [comment]
Can you please issue a pr with your suggested changes? @vonzshik 
When i do it, we need another member with ``contributor`` access rights, which could increase the wait time 😅

**Comment by JKamsker** [comment]
I have created a new pullrequest. Reviews would be appreciated https://github.com/mbdavid/LiteDB/pull/2566

**Comment by JKamsker** [comment]
I have created a new pullrequest. Reviews would be appreciated https://github.com/mbdavid/LiteDB/pull/2566 @vonzshik
