### ISSUE TITLE
InvalidCastExceptions are very hard to debug

### ISSUE THREAD

**Issue by henon** [mbdavid/LiteDB#272]
`********************************************************************************
## InvalidCastException: "Specified cast is not valid."

```
 at _(Object , Object )
 at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value) in e:\LiteDB\LiteDB\Serializer\Mapper\BsonMapper.Deserialize.cs:line 262
 at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value) in e:\LiteDB\LiteDB\Serializer\Mapper\BsonMapper.Deserialize.cs:line 171
 at LiteDB.BsonMapper.ToObject(Type type, BsonDocument doc) in e:\LiteDB\LiteDB\Serializer\Mapper\BsonMapper.Deserialize.cs:line 21
 at LiteDB.BsonMapper.ToObject[T](BsonDocument doc) in e:\LiteDB\LiteDB\Serializer\Mapper\BsonMapper.Deserialize.cs:line 30
 at LiteDB.LiteCollection`1.d__5.MoveNext() in e:\LiteDB\LiteDB\Core\Collections\Find.cs:line 59
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Linq.Enumerable.Sum(IEnumerable`1 source)
 at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
 at ... somewhere in my applicaton 
```

********************************************************************************`

the exception should be catched, evaluated what can not be casted to what and in which document, then rethrown with that info.

**Comment by mbdavid** [comment]
I will take a look on that to write better error exception

**Comment by henon** [comment]
If it saves you trouble, you can take a look at my patch here:

https://github.com/henon/LiteDB/commit/8424975c6efcdab42925714d90159be7241c82bf

**Comment by mbdavid** [comment]
nice code @henon, please, create a pull request to master, I will merge this weekend for 2.0.1 version

**Comment by henon** [comment]
I could, but since I can't compile C#6 I had first to change two or three other things. I created the pull request and also formatted just the one commit as patch attached. You decide which to use.

[0001-in-BsonMapper-generate-meaningful-error-info-on-cast.patch.txt](https://github.com/mbdavid/LiteDB/files/426348/0001-in-BsonMapper-generate-meaningful-error-info-on-cast.patch.txt)

PS: Thanks for this great library!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
