### ISSUE TITLE
[Question] Handling old database files

### ISSUE THREAD

**Issue by mcmonkey4eva** [mbdavid/LiteDB#398]
```
System.NotImplementedException: The method or operation is not implemented.
   at LiteDB.ByteReader.ReadBsonValue(UInt16 length) in C:\Github\LiteDB\LiteDB\Utils\ByteReader.cs:line 152
   at LiteDB.IndexPage.ReadContent(ByteReader reader) in C:\Github\LiteDB\LiteDB\Engine\Pages\IndexPage.cs:line 53
   at LiteDB.BasePage.ReadPage(Byte[] buffer) in C:\Github\LiteDB\LiteDB\Engine\Pages\BasePage.cs:line 165
   at LiteDB.PageService.GetPage[T](UInt32 pageID) in C:\Github\LiteDB\LiteDB\Engine\Services\PageService.cs:line 38
   at LiteDB.IndexService.GetNode(PageAddress address) in C:\Github\LiteDB\LiteDB\Engine\Services\IndexService.cs:line 325
   at LiteDB.IndexService.Find(CollectionIndex index, BsonValue value, Boolean sibling, Int32 order) in C:\Github\LiteDB\LiteDB\Engine\Services\IndexService.cs:line 367
   at LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc) in C:\Github\LiteDB\LiteDB\Engine\Engine\Update.cs:line 65
   at LiteDB.LiteEngine.<>c__DisplayClass1_0.<Upsert>b__0(CollectionPage col) in C:\Github\LiteDB\LiteDB\Engine\Engine\Upsert.cs:line 37
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action) in C:\Github\LiteDB\LiteDB\Engine\Engine\Transaction.cs:line 93
   at LiteDB.LiteEngine.Upsert(String collection, BsonDocument doc) in C:\Github\LiteDB\LiteDB\Engine\Engine\Upsert.cs:line 17
```

That's upserting an ordinary BsonDocument where the `_id` is a length:12 byte array. (`new BsonValue(byte[] value)`)

EDIT: Do note that due to release configuration, line numbers are not exact!

**Comment by mcmonkey4eva** [comment]
It looks like the `BsonType` is missing or invalid, looking at the relevant code...

**Comment by mcmonkey4eva** [comment]
Oh woops, had an old database file I forgot to delete!

So, new question: Will we ever be able to hope for a database update method, or will I have to never update my LiteDB version after pushing my program as production ready?

**Comment by mbdavid** [comment]
If you have an old version (v2) you can just use "upgrade=true" in connection string. This will upgrade, if needs, to v3.

**Comment by mcmonkey4eva** [comment]
Oh awesome! That's good to know. Thanks!
