### ISSUE TITLE
v3.0.0 - beta3 - Possible Timeout Bug with Multi-process read/write

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#406]
This is possibly not a problem, but I'd thought I'd check...

When I test with agressive multi-process read/writing I intermittently get the following exception when trying to call MoveNext on the read iterator:

```
LiteDB.LiteException: Timeout. Database is locked for more than 00:00:00.
   at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
   at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
   at LiteDB.FileDiskService.<ReadJournal>d__24.MoveNext()
   at LiteDB.TransactionService.Recovery()
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
   at LiteDB.LiteDatabase.<>c__DisplayClass10_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()

```

Less often, I get a similar exception when writing from a separate writer process:

```
Unhandled Exception: LiteDB.LiteException: Timeout. Database is locked for more than 00:00:00.
   at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
   at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
   at LiteDB.FileDiskService.WriteJournal(ICollection`1 pages)
   at LiteDB.TransactionService.Commit()
   at LiteDB.LiteEngine.Commit()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs)
   at LiteDB.LiteEngine.Upsert(String collection, BsonDocument doc)
   at LiteDB.LiteCollection`1.Upsert(BsonValue id, T document)
```

I raise this only because I notice that the `WriteJournal()` and `ReadJournal()` methods in LiteDB call `TryLock()` with `TimeSpan.Zero`. **I want to confirm that this is correct and, perhaps, they should not be called with a millisecond or several millisecond retry interval?**

**Comment by kuiperzone** [comment]
PS. I find that I can make my agressive read/write test work reliably if I wrap the Upsert() and MoveNext() calls in a try-catch block. In the event of a LiteDB exception, I sleep for 2ms and then try one more time.

**Comment by mbdavid** [comment]
Hi @kuiperzone, I'm guessing it's same bug as #399. `Find` (in LiteCollection) has a bug on multi thread locking. The same problem doesnt happend using `Find` from LiteEngine.

**Comment by kuiperzone** [comment]
Not sure I follow. They look different to me.

Timeout exception != InvalidCast exception.

**Comment by mbdavid** [comment]
Both errors are about locking problem. When I wrote unit test about this, sometimes I got timeout and sometimes get invalid cast.

**Comment by mbdavid** [comment]
@kuiperzone, anwsering your question about zero timeout on Read/Write journal:

- When you open datafile, if exists journal file with NO one using it's must be recovery your datafile. So, I try lock with no timeout. 
- When you are writing in journal, lock is just to ensure that, if someone are try open will not happend. There is not state where you can 2 process tring to write at same time (write in journal is on Reserved state only).

I'm made more one if condition to avoid read when is not nedded. Try with lastest master version

**Comment by kuiperzone** [comment]
My unit test pass consistently now. However, I do occasionally (perhaps 1 time out of 5) notice the following output in the console area:

```
NUnit Adapter 3.6.1.0: Test execution started
Running selected tests in E:\TRAL-2.0\SOURCE\TictocDB.Test\bin\Release\TictocDB.Test.dll
NUnit3TestExecutor converted 29 of 29 NUnit test cases
System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.StreamExtensions.TryUnlock(FileStream stream, Int64 position, Int64 length)
   at LiteDB.FileDiskService.Unlock(LockState state)
   at LiteDB.LockService.<LockShared>b__13_1()
   at LiteDB.LockService.<>c__DisplayClass10_0.<Shared>b__0()
   at LiteDB.LockControl.Dispose(Boolean disposing)
   at LiteDB.LockControl.Finalize()
   at LiteDB.StreamExtensions.TryUnlock(FileStream stream, Int64 position, Int64 length)
   at LiteDB.FileDiskService.Unlock(LockState state)
   at LiteDB.LockService.<LockShared>b__13_1()
   at LiteDB.LockService.<>c__DisplayClass10_0.<Shared>b__0()
   at LiteDB.LockControl.Dispose(Boolean disposing)
   at LiteDB.LockControl.Finalize()
NUnit Adapter 3.6.1.0: Test execution complete
```

**Comment by mbdavid** [comment]
hummm... maybe was this new implementation "IDisposable done right" in LockControl. I'm updating this.

**Comment by kuiperzone** [comment]
I've just checked my own test code - yes, I call Dispose() on the read enumerator and on LiteDatabase.

Can you repeat this problem?

**Comment by mbdavid** [comment]
I mean, I write new code in LockControl class implementing a "better" IDisposable way. Maybe that was the problem here, becase `System.NullReferenceException` in `TryUnlock` will be happend only if `stream` are null.

**Comment by kuiperzone** [comment]
If you can't repeat this bug, let me know and I'll produce some test code and let you have it.

**Comment by mbdavid** [comment]
Can you post a snippet when this are still occuring? I will take a look at night

**Comment by kuiperzone** [comment]
Sure, but give me a day or so. I've wrapped your LiteDB in my own thin abstraction layer, so I can't just copy and paste. Will have to write a new test.

**Comment by kuiperzone** [comment]
Test solution attached.

The are two projects built against the latest LiteDB. One project is an external console writer. The other is unit test using NUNIT, but it should be easy to alter it for MS unit test. I've built LiteDB and my projects to .NET version 4.6.

The ConsoleWriter writes a DummyDoc class to directory local the project bin. On each write, it increments the Id and sets several over test values which match the Id. It sleeps for 1 ms, and quits after 10 seconds.

The unit test start ConsoleWriter, waits for 1 second, and then begins reading. It grabs a FindAll() Enumberable and reads through to the end, confirming each value in the document. When it reaches the end of enumerator, it calls Dispose() on it, sleeps for 20 ms, and then calls FindAll() again and repeats. It does this for 10 seconds (the ConsoleWriter will quit 1 second before the test ends).

Now, the test always PASSES. However, around 1 time out 6, the unit test displays the following error when it quits, but still all the Assert tests pass:

```
------ Run test started ------
NUnit Adapter 3.6.1.0: Test execution started
Running selected tests in E:\Scratch\ConsoleApplication1\TestProject\bin\Release\TestProject.dll
NUnit3TestExecutor converted 1 of 1 NUnit test cases
System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.StreamExtensions.TryUnlock(FileStream stream, Int64 position, Int64 length)
   at LiteDB.FileDiskService.Unlock(LockState state)
   at LiteDB.LockService.<LockShared>b__13_1()
   at LiteDB.LockService.<>c__DisplayClass10_0.<Shared>b__0()
   at LiteDB.LockControl.Dispose(Boolean disposing)
   at LiteDB.LockControl.Finalize()
   at LiteDB.StreamExtensions.TryUnlock(FileStream stream, Int64 position, Int64 length)
   at LiteDB.FileDiskService.Unlock(LockState state)
   at LiteDB.LockService.<LockShared>b__13_1()
   at LiteDB.LockService.<>c__DisplayClass10_0.<Shared>b__0()
   at LiteDB.LockControl.Dispose(Boolean disposing)
   at LiteDB.LockControl.Finalize()
NUnit Adapter 3.6.1.0: Test execution complete
========== Run test finished: 1 run (0:00:11.6551585) ==========
```

Hope this helps.


[ConsoleApplication1.zip](https://github.com/mbdavid/LiteDB/files/687222/ConsoleApplication1.zip)

**Comment by mbdavid** [comment]
Hi @kuiperzone, nice sample, thanks! I remove dispose Action in LockControl on destructor. I read in this site the "right way to implement IDisposable" and try do the same (but not works)

https://lostechies.com/chrispatterson/2012/11/29/idisposable-done-right/

I remove this and made a lot of test and works fine. Please get lastest commit and try too. If persist, tell me.

**Comment by kuiperzone** [comment]
Yeah!

Ran it about a dozen times and no sign of the error.

Well done! :)
