### ISSUE TITLE
Is litedb can work in xp?

### ISSUE THREAD

**Issue by wincpt** [mbdavid/LiteDB#44]
I have a winform program use litedb,it work in win7 ,but in xp it work failure.
I use litedb shell open db file,in win7 work correct.in xp it have error
>open message.db
>db.JCYB.find
    Oject reference not set an instance of an object.

in my program log the error stack is follow:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.IndexNode.IsHeadTail(CollectionIndex index)
   at LiteDB.IndexService.<FindAll>d__2.MoveNext()
   at LiteDB.LiteCollection`1.EnsureIndex(String field, IndexOptions options)
   at LiteDB.LiteCollection`1.EnsureIndex(String field, Boolean unique)
   at LiteDB.Query.Run[T](LiteCollection`1 collection)
   at LiteDB.LiteCollection`1.<Find>d__9.MoveNext()
   at System.Linq.Enumerable.<SkipIterator>d__4d`1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__3a`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

**Comment by fancymax** [comment]
you need to uncheck "optimize code" in project generate setting，then it will work normal in xp.

**Comment by fancymax** [comment]
你在VS的编译选项中去掉对“优化代码”的勾选，再编译生成即可正常。希望能对你有用。
