### ISSUE TITLE
DropCollection fails with System.NotImplementedException

### ISSUE THREAD

**Issue by rdstevens** [mbdavid/LiteDB#46]
I've made a minimal unit test, which doesn't show this behaviour.

I suspect it may be related to the collection type?

Test method threw exception: 
System.NotImplementedException: The method or operation is not implemented.
Result StackTrace:	
at LiteDB.BinaryReaderExtensions.ReadBsonValue(BinaryReader reader, UInt16 length)
   at LiteDB.IndexPage.ReadContent(BinaryReader reader)
   at LiteDB.DiskService.<>c__DisplayClass1`1.<ReadPage>b__0()
   at LiteDB.DiskService.TryExec(TimeSpan timeout, Action action)
   at LiteDB.DiskService.ReadPage[T](UInt32 pageID)
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.GetNode(PageAddress address)
   at LiteDB.IndexService.<FindAll>d__2.MoveNext()
   at LiteDB.CollectionService.Drop(CollectionPage col)
   at LiteDB.LiteCollection`1.Drop()
   at LiteDB.LiteDatabase.DropCollection(String name)
   at Accord.Service.AccordService.Reset() in 

snip

**Comment by mbdavid** [comment]
In this method ReadBsonValue throws a NotImplementedException when there read a invalid BSON data type. But, in theory, this will never to happend, only if your file is corrupted. Its always happing? It's with only 1 datafile?

**Comment by rdstevens** [comment]
It's always happening.

This is within a UnitTest of my application, so it's repeatable. The byte value read back is 255 - hence the invalid data type.

I'm trying to get a minimal repro, but so far no luck.

I can send you the failing file if that's useful?

**Comment by mbdavid** [comment]
Yes, please! Are you using concurrence insert/update/delete operations?

**Comment by rdstevens** [comment]
No, this is a single-threaded test.

The only thing I'm doing which is dodgy is the test is failing (terminating hard) before completion - which means the database isn't being disposed.

**Comment by rdstevens** [comment]
Database file attached.

The collection is called "jobStore".

Regards,
Rob

**Comment by rdstevens** [comment]
In case the file doesn't make it through email/github, here's a link: https://www.dropbox.com/s/7fy59ri4dfid66x/accord-does-not-drop.db?dl=0

**Comment by mbdavid** [comment]
Strange, in LiteDB shell collections was drop if no problems. 

```
> dump
Dump - Only Disk
0000 <----,----> [Header] 0000  | Change: 5, Version: 1, FreeEmptyPageID: ----, LastPageID: 0003, ColID: 0001
0001 <0000,----> [Collec] 0000  | 'jobStore', Count: 4, FreeDataPageID: 0003, Indexes = [0] Field: '_id', Head: 0002:0, FreeIndexPageID: 0002 /
0002 <0000,----> [Index ] 3103  | [0] Key: -oo, Data: ----:-- / [1] Key: +oo, Data: ----:-- / [2] Key: fa43c210-4523-44a4-97f2-99efef99d1a2, Data: 0003:0 / [3] Key: 07f4c714-42fb-437d-bf2c-1a8278c8dd42, Data: 0003:1 / [4] Key: 0463c159-85af-4329-a7ee-62f76ed2d65d, Data: 0003:2 / [5] Key: f6e85ba2-6013-40bf-a613-0d06baaa26db, Data: 0003:3 /
0003 <0000,----> [Data  ] 3243  | [0] BytesUsed: 105 / [1] BytesUsed: 105 / [2] BytesUsed: 105 / [3] BytesUsed: 105 /

> db.jobStore.find
[1]: {"_id":{"$guid":"0463c159-85af-4329-a7ee-62f76ed2d65d"},"creationDate":{"$date":"2001-01-01T00:00:00.0000000Z"},"priority":0,"userID":"job3","lastUpdated":{"$date":"0001-01-01T02:00:00.0000000Z"}}
[2]: {"_id":{"$guid":"07f4c714-42fb-437d-bf2c-1a8278c8dd42"},"creationDate":{"$date":"2001-01-01T00:00:00.0000000Z"},"priority":0,"userID":"job2","lastUpdated":{"$date":"0001-01-01T02:00:00.0000000Z"}}
[3]: {"_id":{"$guid":"f6e85ba2-6013-40bf-a613-0d06baaa26db"},"creationDate":{"$date":"2001-01-01T00:00:00.0000000Z"},"priority":0,"userID":"job4","lastUpdated":{"$date":"0001-01-01T02:00:00.0000000Z"}}
[4]: {"_id":{"$guid":"fa43c210-4523-44a4-97f2-99efef99d1a2"},"creationDate":{"$date":"2001-01-01T00:00:00.0000000Z"},"priority":0,"userID":"job1","lastUpdated":{"$date":"0001-01-01T02:00:00.0000000Z"}}

> db.jobStore.drop
true

> dump
Dump - Only Disk
0000 <----,----> [Header] 0000  | Change: 6, Version: 1, FreeEmptyPageID: 0001, LastPageID: 0003, ColID: ----
0001 <0000,0002> [Empty ] 4079  |
0002 <0001,0003> [Empty ] 4079  |
0003 <0002,----> [Empty ] 4079  |

> db.jobStore.find
no documents
```

**Comment by mbdavid** [comment]
When you interrupt program during write operations, database can be stay in corrupted state. When you call again, recovery file will be called and fix inconsistent pages.

**Comment by rdstevens** [comment]
I see identical behaviour in LiteDB.Shell too.

```
> db.jobStore.find
[1]: {"_id":{"$guid":"0463c159-85af-4329-a7ee-62f76ed2d65d"},"creationDate":{"$date":"2001-01-01T00:00:00.0000000Z"},"priority":0,"userID":"job3","lastUpdated":
{"$date":"0001-01-01T00:00:00.0000000Z"}}
[2]: {"_id":{"$guid":"07f4c714-42fb-437d-bf2c-1a8278c8dd42"},"creationDate":{"$date":"2001-01-01T00:00:00.0000000Z"},"priority":0,"userID":"job2","lastUpdated":
{"$date":"0001-01-01T00:00:00.0000000Z"}}
[3]: {"_id":{"$guid":"f6e85ba2-6013-40bf-a613-0d06baaa26db"},"creationDate":{"$date":"2001-01-01T00:00:00.0000000Z"},"priority":0,"userID":"job4","lastUpdated":
{"$date":"0001-01-01T00:00:00.0000000Z"}}
[4]: {"_id":{"$guid":"fa43c210-4523-44a4-97f2-99efef99d1a2"},"creationDate":{"$date":"2001-01-01T00:00:00.0000000Z"},"priority":0,"userID":"job1","lastUpdated":
{"$date":"0001-01-01T00:00:00.0000000Z"}}
> dump
Dump - Only Disk
0000 <----,----> [Header] 0000  | Change: 5, Version: 1, FreeEmptyPageID: ----, LastPageID: 0003, ColID: 0001
0001 <0000,----> [Collec] 0000  | 'jobStore', Count: 4, FreeDataPageID: 0003, Indexes = [0] Field: '_id', Head: 0002:0, FreeIndexPageID: 0002 /
0002 <0000,----> [Index ] 3103  | [0] Key: -oo, Data: ----:-- / [1] Key: +oo, Data: ----:-- / [2] Key: fa43c210-4523-44a4-97f2-99efef99d1a2, Data: 0003:0 / [3]
Key: 07f4c714-42fb-437d-bf2c-1a8278c8dd42, Data: 0003:1 / [4] Key: 0463c159-85af-4329-a7ee-62f76ed2d65d, Data: 0003:2 / [5] Key: f6e85ba2-6013-40bf-a613-0d06baa
a26db, Data: 0003:3 /
0003 <0000,----> [Data  ] 3243  | [0] BytesUsed: 105 / [1] BytesUsed: 105 / [2] BytesUsed: 105 / [3] BytesUsed: 105 /

> db.jobStore.drop
true
> dump
Dump - Only Disk
0000 <----,----> [Header] 0000  | Change: 6, Version: 1, FreeEmptyPageID: 0001, LastPageID: 0003, ColID: ----
0001 <0000,0002> [Empty ] 4079  |
0002 <0001,0003> [Empty ] 4079  |
0003 <0002,----> [Empty ] 4079  |

>
```

**Comment by rdstevens** [comment]
Debugging:

In IndexPage.ReadContent the call to reader.ReadBsonValue has a parameter value of zero.

node.Position is 2:0
node.KeyLength is 0

I suspect issuing a zero length read to reader.ReadBsonValue is yielding the 255 return code.


My test is single threaded, but is appears the LiteDB watchdog thread is building an index at the same time?

**Comment by rdstevens** [comment]
The two threads (un-named worker thread) and the watchdog thread seem to be sharing an instance of the reader (same hash code).

Are they racing to read the same file? Is the file position being destroyed by the indexer?

**Comment by mbdavid** [comment]
LiteDB is no thread safe, so if two threads chage same object reference it's will be a problem.

You can have 2 (or more) instances of LiteDatabase connected in same data file.

**Comment by rdstevens** [comment]
Ah... That's probably my watchdog thread doing the stomping.

I'll get back on this tomorrow.

Thanks,
Rob

**Comment by rdstevens** [comment]
Yes - I confirm that is my watchdog thread.

So, as you first suspected, this is a user error!

Cheers,
Rob
