### ISSUE TITLE
LiteDB Regex serialization issue

### ISSUE THREAD

**Issue by 0xFireball** [mbdavid/LiteDB#515]
I am calling `Upsert` on a POCO instance of a class `OMServerState` that looks like this (other referenced classes are also included):

```csharp
    public class OMServerState
    {
        public List<ApiAccessKey> ApiKeys { get; set; } = new List<ApiAccessKey>();

        // Proxy to context
        public OMDbServiceState DbServiceState { get; set; }

        /// <summary>
        /// BsonDocument ID
        /// </summary>
        [BsonId]
        public ObjectId DatabaseId { get; set; }

        [BsonIgnore]
        public LiteCollection<OMServerState> PersistenceMedium { get; set; }

        [BsonIgnore]
        public Action Persist { get; set; }
    }
    public class OMDbServiceState
    {
        public Dictionary<string, List<SecurityRule>> SecurityRuleTable { get; set; } = new Dictionary<string, List<SecurityRule>>();
    }
    public class ApiAccessKey
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("accessScopes")]
        public ApiAccessScope[] AccessScopes { get; set; } = new ApiAccessScope[0];
    }
    public class SecurityRule
    {
                /// <summary>
        /// Compiled path regex
        /// </summary>
        [JsonProperty("pathRegex")]
        public Regex PathRegex { get; set; }

        /// <summary>
        /// The actions that this rule applies to
        /// </summary>
        [JsonProperty("actions")]
        public DatabaseAction Actions { get; set; }

        [JsonProperty("priority")]
        public int Priority { get; set; }

        [JsonProperty("allow")]
        public bool Allow { get; set; }

        /// <summary>
        /// A unique identifier for the rule
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }
    }
```

Note: `DatabaseAction` is a flags enum. `ApiAccessScope` is an enum.

[This](https://github.com/0xFireball/OsmiumMine.Core/blob/294c70f8c52aeb0d82659aef42bf8413a8d85398/OsmiumMine.Core/OsmiumMine.Core.Server/Configuration/OMServerConfigurator.cs#L44) is the call that is giving me an issue.

On that call, I get an `ArgumentException: Static property requires null instance, non-static property requires non-null instance`

Here are more exception details:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=Static property requires null instance, non-static property requires non-null instance.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at LiteDB.Reflection.CreateGenericGetter(Type type, MemberInfo memberInfo)
   at LiteDB.BsonMapper.BuildEntityMapper(Type type)
   at LiteDB.BsonMapper.GetEntityMapper(Type type)
   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.SerializeArray(Type type, IEnumerable array, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.SerializeDictionary(Type type, IDictionary dict, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   at LiteDB.BsonMapper.ToDocument(Type type, Object entity)
   at LiteDB.BsonMapper.ToDocument[T](T entity)
   at LiteDB.LiteCollection`1.Upsert(T document)
... // my application stack trace
```

Code samples of what I trying to do are linked.

**Comment by 0xFireball** [comment]
Looks like the problem is coming from the `Dictionary<string, List<SecurityRule>>`. When that dictionary is empty, the issue does not occur.

However, shouldn't LiteDB be able to handle dictionaries and lists?

**Comment by 0xFireball** [comment]
@mbdavid I have verified that this following code can reproduce the issue:

```csharp
                var x = new Dictionary<string, List<SecurityRule>>();
                var l = new List<SecurityRule>();
                l.Add(new SecurityRule("/*"));
                x.Add("test", l);
                var doc = BsonMapper.Global.ToDocument(x.GetType(), x);
```

**Comment by 0xFireball** [comment]
@mbdavid 
I have a sample program that will reproduce the issue with the latest stable LiteDB (`3.0.1`)

```csharp
using LiteDB;
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace LiteDbIssue515
{
    public class BrokenClass
    {
        public Regex PathRegex { get; set; }

        public int Actions { get; set; }

        public int Priority { get; set; }

        public bool Allow { get; set; }

        public string Id { get; set; }

        public BrokenClass(string rgd)
        {
            PathRegex = new Regex(rgd);
            Id = Guid.NewGuid().ToString("N");
        }
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var x = new Dictionary<string, List<BrokenClass>>();
            var l = new List<BrokenClass>();
            l.Add(new BrokenClass("/*"));
            x.Add("test", l);
            var doc = BsonMapper.Global.ToDocument(x.GetType(), x);
        }
    }
}
```

(this is on .NET Core 1.0)

**Comment by 0xFireball** [comment]
I have traced the problem to this line:
`public Regex PathRegex { get; set; }`

when it's a string, there is no problem. It looks like LiteDB just cannot handle `Regex`.

**Comment by 0xFireball** [comment]
OK, I have solved the problem.
Adding this simple `BsonMapper` entry will prevent the error.

```csharp
            // Register a Regex BSONMapper
            BsonMapper.Global.RegisterType<Regex>(
                serialize: r => r.ToString(),
                deserialize: d => new Regex(d.AsString)
            );
```

**Comment by mbdavid** [comment]
Hi @0xFireball, I will add this `Regex` custom type inside LiteDB (with or without `RegexOptions`)
