### ISSUE TITLE
Concurrency: exception when using same collection from multiple threads 

### ISSUE THREAD

**Issue by dimzon** [mbdavid/LiteDB#560]
I'm trying to use LiteDB as inprocess persistent TASK|JOB QUEUE
Unfortunally it doesn't work
```
using System;
using System.Threading;
using LiteDB;

namespace perfTest0
{
    public class Task
    {
        [BsonId]
        public ObjectId TaskID { get; set; }

        [BsonField("n")]
        [BsonIndex(false)]
        public DateTime NextCheck { get; set; }
    }

    class Program
    {
        private void Doit()
        {
            var r = new Random();
            using (var db = new LiteDB.LiteDatabase("MyData.queue"))
            {
                var col = db.GetCollection<Task>("testTasks000");

                Action foo = delegate
                {
                    var c = db.GetCollection<Task>("testTasks000");
                    for (;;)
                    {
                        using (var t = db.BeginTrans())
                        {
                            c.Insert(new Task());
                            t.Commit();
                        }
                        Thread.Sleep(1000);
                    }

                };
                foo.BeginInvoke(null, null);

                for (;;)
                {
                    using (var tran = db.BeginTrans())
                    {
                        var dt = DateTime.Now;
                        var findOne = col.FindOne(Query.All("n", Query.Ascending));

                        if (findOne != null)
                        {
                            if (findOne.NextCheck <= dt)
                            {
                                Thread.Sleep(10);
                                if (r.NextDouble() > 0.2)
                                {
                                    findOne.NextCheck = dt.AddSeconds(1);
                                    col.Update(findOne);
                                }
                                else
                                {
                                    col.Delete(findOne.TaskID);
                                }

                            }
                            else
                            {
                                Console.WriteLine(findOne);
                                Thread.Sleep(500);
                                continue;
                            }
                        }
                        else
                        {
                            Thread.Sleep(500);
                            continue;
                        }
                        tran.Commit();
                    }
                }

            }
        }

        static void Main(string[] args)
        {
            new Program().Doit();
        }
    }
}
```
```System.Threading.SynchronizationLockException was unhandled
  HResult=-2146233064
  Message=The write lock is being released without being held.
  Source=System.Core
  StackTrace:
       at System.Threading.ReaderWriterLockSlim.ExitWriteLock()
       at LiteDB.LockService.<ThreadWrite>b__17_2()
       at LiteDB.LockService.<>c__DisplayClass11_0.<Reserved>b__0()
       at LiteDB.LockControl.Dispose()
       at LiteDB.LiteEngine.Rollback()
       at LiteDB.LiteTransaction.Dispose()
       at perfTest0.Program.Doit() in c:\Users\Alexandrovda\Documents\Visual Studio 2013\Projects\perfTest0\perfTest0\Program.cs:line 91
       at perfTest0.Program.Main(String[] args) in c:\Users\Alexandrovda\Documents\Visual Studio 2013\Projects\perfTest0\perfTest0\Program.cs:line 99
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by mbdavid** [comment]
Hi @dimzon, do not use transaction when you are sharing same LiteDatabase instance across threads.

**Comment by QJonny** [comment]
Hello @mbdavid, are you going to support this in a future release?

**Comment by mbdavid** [comment]
Hi @QJonny, my plans is remove transaction for next major version, like others nosql databases. ACID will be for document only level.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
