### ISSUE TITLE
Getting exception `Operation could destabilize the runtime.`

### ISSUE THREAD

**Issue by shytikov** [mbdavid/LiteDB#563]
Hi,

I'm getting way beyond strange error when try to convert to `BSON` object from MS CRM SDK. Here is my test method (it's in file `ComplexTypeTest.cs`, line numbers in the file are the same as line numbers in snippet):

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Xrm.Sdk;

namespace LiteDB.Tests.Document
{
    [TestClass]
    public class ComplexTypeTest
    {
        [TestMethod]
        public void ComplexType_Test()
        {
            var mapper = new BsonMapper();
            var o = new Entity("account");

            var doc = mapper.ToDocument(o);
        }
    }
}
```

I would expect it not serialize fully, or correctly, but `Operation could destabilize the runtime`???

To reproduce error, please add `Microsoft.CrmSdk.CoreAssemblies/6.1.2` nuget package.

As far I can see, it creates mapper, which contains property `Item`. While this property is invisible normally (it is protected I guess), or hidden in any other way, it shows this exception.

Here is the stack trace:

```
   at lambda_method(Closure , Object )
   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth) in C:\Workspace\shytikov\LiteDB\LiteDB\Mapper\BsonMapper.Serialize.cs:line 165
   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth) in C:\Workspace\shytikov\LiteDB\LiteDB\Mapper\BsonMapper.Serialize.cs:line 119
   at LiteDB.BsonMapper.ToDocument(Type type, Object entity) in C:\Workspace\shytikov\LiteDB\LiteDB\Mapper\BsonMapper.Serialize.cs:line 21
   at LiteDB.BsonMapper.ToDocument[T](T entity) in C:\Workspace\shytikov\LiteDB\LiteDB\Mapper\BsonMapper.Serialize.cs:line 29
   at LiteDB.Tests.Document.ComplexTypeTest.ComplexType_Test() in C:\Workspace\shytikov\LiteDB\LiteDB.Tests\Mapper\ComplexTypeTest.cs:line 20
```

Would appreciate any clue how to workaround this issue.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
