### ISSUE TITLE
Failed to create instance for type 'TestLiteDb.Program+Employee' from assembly

### ISSUE THREAD

**Issue by sherry-ummen** [mbdavid/LiteDB#57]
Hello here is again my small test program which is not working. Failign with following

Exception: Failed to create instance for type 'TestLiteDb.Program+Employee' from assembly

Stack Trace: 
   at LiteDB.Reflection.CreateInstance(Type type)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection`1.<Find>d__27.MoveNext()
   at TestLiteDb.Program.Main(String[] args) in d:\OneDrive\Edu\C#\TestLiteDb\TestLiteDb\Program.cs:line 54
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```C#
        [Serializable]
        public class Employee {
            [BsonId]
            public string EmployeeID { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public List<string> Objects { get; set; }
            public byte[] Bytearray { get; set; }
        }

 using (var db = new LiteDatabase(@"filename=D:\LiteDb\MyData.db;journal=false")) {
                // Get a collection (or create, if not exits)
                var col = db.GetCollection<Employee>("customers");
                var timer = new Stopwatch();
                timer.Start();
                foreach (var index in Enumerable.Range(1, 10000)) {
                    var emp = new Employee() {
                        EmployeeID = "wyu" + index,
                        FirstName = "one",
                        LastName = "two",
                        //Bytearray = new byte[1 * 1000 * 1000]
                    };
                     col.Insert(emp);
                }
                var de = col.FindAll();

                foreach (var dd in de) { // Fails HERE
                    Console.Write(dd.EmployeeID);
                }

                timer.Stop();
                Console.WriteLine("Time taken {0} ms", timer.ElapsedMilliseconds);
            }
            Console.ReadKey();

```

**Comment by mbdavid** [comment]
I made the same example, using VS2015, Windows 10 x64 and works fine. I try using .NET 4, 4.5, 4,5.2 and all works fine (using LiteDB 1.0.3 from NuGet).

`Time taken 3780 ms`

- This data file already exists?
- Witch your windows/.NET version?
- Did you try get source and run all Unit tests? Are working for you?

**Comment by sherry-ummen** [comment]
Hmm interesting. I have been runnign locally using a different project. You can try out my .sln from here http://1drv.ms/1PWBU18

**Comment by sherry-ummen** [comment]
aah ha found the problem, if I keep the class as internal class then it fails if I move the class out of the main class then it works. So its a bug ?

**Comment by mbdavid** [comment]
It's - classes must be public. It's not a bug, but to use IL fast instance classes must be public. Take a look on https://github.com/mbdavid/LiteDB/wiki/Object-Mapping

**Comment by sherry-ummen** [comment]
Sorry missed that. Thanks
