### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path is denied.

### ISSUE THREAD

**Issue by mciureanu** [mbdavid/LiteDB#643]
This following piece of code triggers this exception, at a random time.

            var path = "FileDb/FileDb.db";

            for (int i = 0; i < 200; i++)
            {
                //Thread.Sleep(5);
                Console.WriteLine(i);
                using (var db = new LiteDatabase(path))
                {
                    var collection = db.GetCollection<Customer>("customers");
                    var customer = new Customer
                    {
                        Name = "John Doe",
                        Phones = new string[] { "8000-0000", "9000-0000" },
                        IsActive = true
                    };
                    collection.Insert(customer);
                }
            }

System.UnauthorizedAccessException: Access to the path '...\FileDb\FileDb-journal.db' is denied.
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LiteDB.FileDiskService.<ReadJournal>d__22.MoveNext()
   at LiteDB.TransactionService.Recovery()
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.Insert(T document)
   at DIH.Core.Sync.Infrastructure.Tests.LiteDb.TestLiteDbBug.TestBug() 

- If using Async = true, the same exception appears (but not for the journal file, but the main database).
- If using no journaling, it works.
- Putting Thread.Sleep(5) makes it work again, so maybe some part of the operation is async, and the file is not really closed at the end for a very short amount of time.

**Comment by arqeco** [comment]
Read this https://github.com/mbdavid/LiteDB/issues/746

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
