### ISSUE TITLE
NullReferenceException while calling Count()

### ISSUE THREAD

**Issue by anidotnet** [mbdavid/LiteDB#664]
While calling Count method on an empty collection, I am getting NRE. Here is the stacktrace

Error while saving to database: System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.StreamExtensions.<>c__DisplayClass4_0.<TryLock>b__0()
   at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
   at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
   at LiteDB.FileDiskService.Lock(LockState state, TimeSpan timeout)
   at LiteDB.LockService.LockShared()
   at LiteDB.LockService.Shared()
   at LiteDB.LiteEngine.Count(String collection, Query query)
   at LiteDB.LiteCollection`1.Count()

I am accessing the database synchronously on UI thread only. I am on .Net framework 4, Windows 10-64bit.

**Comment by anidotnet** [comment]
My Bad. Db was getting disposed before calling the Count(). Closing the issue.
