### ISSUE TITLE
Error thrown when creating index on decimal

### ISSUE THREAD

**Issue by ByronAP** [mbdavid/LiteDB#693]
I am bulk loading my data of aprox 130k items. Then I create my indexes, one of which needs to be on a decimal value of at least 14,8 precision which is well within .net decimal. The EnsureIndex command always fails with

"System.NotImplementedException: The method or operation is not implemented.
   at LiteDB.ByteWriter.WriteBsonValue(BsonValue value, UInt16 length)
   at LiteDB.IndexPage.WriteContent(ByteWriter writer)
   at LiteDB.BasePage.WritePage()
   at LiteDB.TransactionService.Commit()
   at LiteDB.LiteEngine.Commit()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)"

and since the index can not be created queries fail as well. The same code works for double, is decimal not implemented?

may be related to issue #386

**Comment by mbdavid** [comment]
Bingo! Thanks @ByronAP! This method (WriteBsonValue) it´s only used in write index key. I never created an index in decimal. I'm fixing this...
