### ISSUE TITLE
Concurrent read/write failures

### ISSUE THREAD

**Issue by stojy** [mbdavid/LiteDB#78]
Using LiteDB 1.0.4, I'm getting failures when performing reads (e.g.FindAll) and writes (e.g. Insert, Update) from different threads at the same time.

As far as I can tell, I'm using LiteDB correctly whereby each thread has it's own instance of the database which is disposed when no longer needed.

This issue is potentially related to #73, however I'm receiving different exceptions.  The workaround I've used to overcome the issue is to thread lock all DB access, but unfortunately this isn't a viable long term solution due to performance hit when servicing simultaneous access from our users (a small web site).

Below are the unique exceptions with stack traces that I've seen.

	LiteDB.LiteException: Failed to create instance for type 'System.Collections.Generic.List`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' from assembly 'System.Collections.Generic.List`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Checks if has a public constructor with no parameters
	   at LiteDB.Reflection.CreateInstance(Type type)
	   at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
	   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
	   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
	   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
	   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
	   at LiteDB.LiteCollection`1.<Find>d__9.MoveNext()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

	System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
	   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	   at LiteDB.LiteCollection`1.<Find>d__9.MoveNext()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

	LiteDB.LiteException: Timeout. Database is locked for more than 00:01:00
	   at LiteDB.DiskService.TryExec(TimeSpan timeout, Action action)
	   at LiteDB.JournalService.CreateJournalFile(Action action)
	   at LiteDB.TransactionService.Commit()
	   at LiteDB.LiteCollection`1.Insert(T document)

	- only seen this when LiteDB automatically creates the .db file
	System.IO.IOException: The process cannot access the file 'C:\code\distribution\RWWA.Distribution\RWWA.Deployment.Tests\bin\Debug\dummy.db' because it is being used by another process.
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
	   at LiteDB.DiskService.CreateNewDatafile(ConnectionString connectionString)
	   at LiteDB.LiteDatabase..ctor(String connectionString)

	System.NullReferenceException: Object reference not set to an instance of an object.
	   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
	   at LiteDB.BsonMapper.GetPropertyMapper(Type type)
	   at LiteDB.BsonMapper.SetAutoId(Object entity, LiteCollection`1 col)
	   at LiteDB.LiteCollection`1.Insert(T document)

	System.UnauthorizedAccessException: Access to the path 'C:\code\distribution\RWWA.Distribution\RWWA.Deployment.Tests\bin\Debug\dummy-journal.db' is denied.
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
	   at LiteDB.RecoveryService.OpenExclusiveFile(String filename, Action`1 success)
	   at LiteDB.LiteDatabase..ctor(String connectionString)

	[I didn't log this exception type]: DB.IndexService.GetNode(PageAddress address)
	   at LiteDB.IndexService.<FindAll>d__2.MoveNext()
	   at LiteDB.LiteCollection`1.<Find>d__9.MoveNext()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

All of the above were re-created with the below code.

    using System;
    using System.Linq;
    using System.Threading;
    using System.Threading.Tasks;
    using CsQuery.ExtensionMethods;
    using LiteDB;
    using NUnit.Framework;

    namespace RWWA.Deployment.Tests
    {
        public class LiteDbTest
        {
            public class Target
            {
                [BsonId]
                public ObjectId Id { get; set; }

                [BsonIndex(true)]
                public string Name { get; set; }

                public DateTime LastUpdateCheck { get; set; }
            }

            [Test]
            public void TestReadInsertUpdate()
            {
                Setup();

                var update = Execute("u", db =>
                {
                    var target = db.GetCollection<Target>("targets").FindOne(x => x.Name != null);
                    if (target != null)
                    {
                        target.LastUpdateCheck = DateTime.Now;
                        db.GetCollection<Target>("targets").Update(target);
                    }
                });
                var insert = Execute("i", db => db.GetCollection<Target>("targets").Insert(CreateTarget()));
                var read = Execute("r", db => db.GetCollection<Target>("targets").FindAll().ToList());
                Task.WaitAll(update, insert, read);
            }

            [Test]
            public void TestReadInsert()
            {
                Setup();

                var insert = Execute("i", db => db.GetCollection<Target>("targets").Insert(CreateTarget()));
                var read = Execute("r", db => db.GetCollection<Target>("targets").FindAll().ToList());
                Task.WaitAll(insert, read);
            }

            [Test]
            public void TestReadUpdate()
            {
                Setup();

                var update = Execute("u", db =>
                {
                    var target = db.GetCollection<Target>("targets").FindOne(x => x.Name != null);
                    if (target != null)
                    {
                        target.LastUpdateCheck = DateTime.Now;
                        db.GetCollection<Target>("targets").Update(target);
                    }
                });
                var read = Execute("r", db => db.GetCollection<Target>("targets").FindAll().ToList());
                Task.WaitAll(update, read);
            }

            private static Target CreateTarget()
            {
                return new Target { Name = Guid.NewGuid().ToString(), LastUpdateCheck = DateTime.Now };
            }

            private static void Setup()
            {
                using (var db = new LiteDatabase("dummy.db"))
                {
                    db.DropCollection("targets");
                    Enumerable.Repeat(0, 1000).ForEach(x => db.GetCollection<Target>("targets").Insert(CreateTarget()));
                }
            }

            private static Task<ParallelLoopResult> Execute(string prefix, Action<LiteDatabase> action)
            {
                return Task.Run(() => Parallel.For(0, 100, x =>
                                                                {
                                                                    Console.Write($"{prefix}-{x}-{Thread.CurrentThread.ManagedThreadId} ");
                                                                    try
                                                                    {
                                                                        using (var db = new LiteDatabase("dummy.db"))
                                                                            action(db);
                                                                    }
                                                                    catch (Exception e)
                                                                    {
                                                                        Console.WriteLine(e);
                                                                    }
                                                                }));
            }
        }
    }

**Comment by mbdavid** [comment]
Hi @stojy! Some errors messages are correct, like timeout and others seams that not all mapper are loaded before concurrency. I will add your unit test to my code to test better. I assume that v1 are not too concurrency and has some bugs about that. I'm working hard to fix them in v2.

**Comment by stojy** [comment]
Hi @mbdavid. That's really good you're looking at improving the concurrency in v2.  LiteDB is a good library and will be doubly so after the concurrency issues are sorted.

Do you know approximately when v2 will be released as a beta/rc?

**Comment by mbdavid** [comment]
Hi @stojy, v2 are building to improve code and consistence. I split code in modules to better maintaince. I guess in one or two weeks I will release a beta version. Than, I need write more unit tests and update site/wiki.

**Comment by mbdavid** [comment]
Hi @stojy, can you test in new v2 beta version?

**Comment by faxedhead** [comment]
I ran these unit tests against v2.0.0-beta and the **TestReadInsert** test fails reproducibly with:

LiteDB.LiteException: Failed to create instance for type 'Processor.Tests.LiteDbTest+Target' from assembly 'Processor.Tests.LiteDbTest+Target, Processor.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. **Checks if has a public constructor with no parameters**
   at LiteDB.Reflection.CreateInstance(Type type)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection`1.<Find>d__31.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Processor.Tests.LiteDbTest.<TestReadInsert>b__7(LiteDatabase db) in c:\Code\Processor\UnitTests\Processor.Tests\Tests.cs:line 51
   at Processor.Tests.LiteDbTest.<>c__DisplayClass15.<Execute>b__14(Int32 x) in c:\Code\Processor\UnitTests\Processor.Tests\Tests.cs:line 95

The 'Target' class **does** have a public constructor with no parameters:

        public class Target
        {
            [BsonId]
            public ObjectId Id { get; set; }

            [BsonIndex(true)]
            public string Name { get; set; }

            public DateTime LastUpdateCheck { get; set; }
        }

So i'm confused why LiteDb is failing with this error.  I'm guess this error is raised due to a concurrency issue, and LiteDb is catching then re-throwing with incorrect advice (as evidenced by the incorrect grammar in the exception message).  Any chance you can take a look at this @mbdavid?

**Comment by mbdavid** [comment]
Hi @faxedhead and @stojy, I found 2 bugs here: a missing `lock` in `Reflection.CreateInstance` on `_cache` reflection ctors and better exception catch on journal files. I added your unit test, take a look on `master` branch.
