### ISSUE TITLE
Add support for Tuples.

### ISSUE THREAD

**Issue by dougheeren** [mbdavid/LiteDB#810]
Test Name:	ShouldReturnTrue_When_ReadingMaps
Test FullName:	TibMap.Repository.Test.RepositoryTest.ShouldReturnTrue_When_ReadingMaps
Test Source:	C:\Users\XX\source\repos\TibMap\TibMap.Repository.Test\RepositoryTest.cs : line 65
Test Outcome:	Failed
Test Duration:	0:00:00.8134955

Result StackTrace:	
at System.Linq.Expressions.Expression.New(Type type)
   at LiteDB.Reflection.CreateClass(Type type)
   at LiteDB.Reflection.CreateInstance(Type type)
--- End of inner exception stack trace ---
    at LiteDB.Reflection.CreateInstance(Type type)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at LiteDB.LiteQueryable`1.<ToEnumerable>d__21.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TibMap.Repository.MapRepository.Read(Expression`1 predicate) in C:\Users\XX\source\repos\TibMap\TibMap.Repository\MapRepository.cs:line 23
   at TibMap.Repository.MapRepository.ReadAll() in C:\Users\XX\source\repos\TibMap\TibMap.Repository\MapRepository.cs:line 39
   at TibMap.Repository.Test.RepositoryTest.ShouldReturnTrue_When_ReadingMaps() in C:\Users\XX\source\repos\TibMap\TibMap.Repository.Test\RepositoryTest.cs:line 67
Result Message:	
Test method TibMap.Repository.Test.RepositoryTest.ShouldReturnTrue_When_ReadingMaps threw exception: 
LiteDB.LiteException: Failed to create instance for type 'System.Tuple`2[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' from assembly 'System.Tuple`2[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Checks if the class has a public constructor with no parameters. ---> System.ArgumentException: Type 'System.Tuple`2[System.Int32,System.Int32]' does not have a default constructor
Parameter name: type

**Comment by WoozChucky** [comment]
Any status update for this ?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
