### ISSUE TITLE
Obtaining System.ArgumentException when loading a Collection

### ISSUE THREAD

**Issue by yoshisman8** [mbdavid/LiteDB#818]
Im trying to execute the function 'find' in a collection of the object type "Character".
The function being is `var C = col.Find(x => x.Name.ToLower().StartsWith(name.ToLower()));` and it returns the following StackTrace:
`System.ArgumentException occurred
  HResult=0x80070057
  Message=Incorrect number of arguments supplied for call to method 'Char get_Chars(Int32)'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at LiteDB.Reflection.CreateGenericGetter(Type type, MemberInfo memberInfo)
   at LiteDB.BsonMapper.BuildEntityMapper(Type type)
   at LiteDB.BsonMapper.GetEntityMapper(Type type)
   at LiteDB.QueryVisitor`1.GetField(Expression expr, String prefix, Boolean showArrayItems)
   at LiteDB.QueryVisitor`1.VisitExpression(Expression expr, String prefix)
   at LiteDB.LiteCollection`1.Find(Expression`1 predicate, Int32 skip, Int32 limit)
   at ERA20.Modules.Classes.Character.GetCharacter(String name) in C:\Users\yoshisman\source\repos\E.R.A.-Discord-Bot\ERA2.0\ERA2.0\Modules\Classes\Actors.cs:line 138`
**EDIT**: Here's the Character (and Actor) class for reference: https://pastebin.com/KK4T3wTu

**Comment by yoshisman8** [comment]
Forgot to add the function that's being run:
`public IEnumerable<Character> GetCharacter(string name)
        {
            var col = Database.GetCollection<Character>("Characters");
            col.EnsureIndex(x => x.Name);
            var C = col.Find(x => x.Name.ToLower().StartsWith(name.ToLower()));
            return C;
        }`
Its a simple function, but it gets that stacktrace when trying to execute it.

**Comment by mbdavid** [comment]
Hi @yoshisman8, there is no support for function (in this way) in LiteDB. If you are using v4, you can create an index to support that, like this:

```
// create index using lower function
col.EnsureIndex("Name", "LOWER($.Name)");

// query using index (using Query helper)
col.Find(Query.StartsWith("Name", name.ToLower()));

// query using Linq (do not use ToLower in field/index name)
col.Find(x => x.Name.StartsWith(name.ToLower())
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
