### ISSUE TITLE
AutoId using interface giving NullPointer

### ISSUE THREAD

**Issue by Br4inFreze** [mbdavid/LiteDB#826]
```csharp 
class Program
    {
        static void Main(string[] args)
        {
            try
            {
                LiteCollection<ICustomer> collection = new LiteDatabase(@"test.db").GetCollection<ICustomer>();
                ICustomer c = new Customer("eden");
                collection.Insert(c);

                c = new Customer("mike");
                collection.Insert(c);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                Console.ReadKey();
            }
        }


    }


    public interface ICustomer
    {
        int Id { get; }
        string Name { get; set; }
    }


    public class Customer : ICustomer
    {
        public Customer()
        {

        }

        public Customer(string name) : this()
        {
            Name = name;
        }


        public string Name { get; set; }
        [BsonId(true)]
        public int Id { get; set; }
    }


```

Running the above code making me catch NullPointerException with the following stacktrace : 

  ```csharp
 at LiteDB.LiteCollection`1.<GetBsonDocs>d__35.MoveNext()
   at LiteDB.LiteEngine.<>c__DisplayClass20_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Program.Main(String[] args) in Program.cs:line 20
```

Am i doing something wrong?
Im trying to implement a autoid on the field Id..

**Comment by 01120** [comment]
@mbdavid

**Comment by mbdavid** [comment]
Hi @01120, I need to be review. I will try do unit test about this, but it's maybe a bug in BsonMapper when try convert your interface to BsonDocument.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
