### ISSUE TITLE
PlatformNotSupportedException in LiteEngine ctor FileDiskService.Lock on Mac OS X using .Net Core 2.1.4

### ISSUE THREAD

**Issue by ryanseghers** [mbdavid/LiteDB#908]
I'm trying to use LiteDB on Mac OS X 10.12.6 (Sierra) using .Net Core 2.1.4. I am getting an exception:

Unhandled Exception: System.PlatformNotSupportedException: Locking/unlocking file regions is not supported on this platform. Use FileShare on the entire file instead.
							at System.IO.FileStream.LockInternal(Int64 position, Int64 length)
							at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
							at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
							at LiteDB.FileDiskService.Lock(LockState state, TimeSpan timeout)
							at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
							at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
							at LiteDB.LazyLoad`1.get_Value()
							at LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)

See the Dec 12 2016 post in this discussion: https://github.com/dotnet/corefx/issues/5964
If I understand this discussion correctly then they have specifically decided not to support this particular locking behavior on Mac OS X, so LiteDB as is will never work.

I would like to use LiteDB on Mac OS X. Am I understanding the issue correctly? Is there any solution to this?

**Comment by mbdavid** [comment]
Hi @ryanseghers, OS X do not  support file lock, so you cann't use LiteDB with lock support (no multi process access). But you can still use LiteDB in multi thread model, using: "Mode=Exclusive" in connection string (exclusive mode do not lock file because open file in exclusive mode

**Comment by mstum** [comment]
FWIW, there is no way to just see if File Locks are supported in .net Core (e.g., no static FileStream.CanLock), the only option apart from hardcoding a list of OS platforms that support it would be to try to open the file during the constructor/init, catch the PlatformNotSupportedException and change the FileMode to .Exclusive.
