### ISSUE TITLE
Connection string parameters InitialSize and Password are incompatible

### ISSUE THREAD

**Issue by spodskubka** [mbdavid/LiteDB#929]
This may be by design, but i haven't found it documented anywhere, so I am reporting this as an issue.

The following code uses LiteDB 4.1.1 and demonstrates the issue:
```csharp
using System;
using System.IO;
using LiteDB;

class Poco
{
    public Guid Id { get; set; }
    public string Text { get; set; }
}

class Program
{
    static void Main()
    {
        var connectionString = new ConnectionString("test.litedb")
        {
            Password = "password",
            InitialSize = 50 * 1024 * 1024,
        };

        File.Delete("test.litedb");
        using (var liteDatabase = new LiteDatabase(connectionString))
        {
            LiteCollection<Poco> pocoCollection = liteDatabase.GetCollection<Poco>();
            pocoCollection.EnsureIndex(poco => poco.Text);
        }
    }
}
```

This is the exception that is happening in the call to `EnsureIndex()`:
```
LiteDB.LiteException: Datafile is not a LiteDB database.
   at LiteDB.HeaderPage.ReadContent(ByteReader reader)
   at LiteDB.BasePage.ReadPage(Byte[] buffer)
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.NewPage[T](BasePage prevPage)
   at LiteDB.CollectionService.Add(String name)
   at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.EnsureIndex(String collection, String field, String expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(String field, String expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex[K](Expression`1 property, Boolean unique)
   at Program.Main() in Program.cs:line 25
```

My guess is
* the pages that are written initially in response to the InitialSize property are not being encrypted
* subsequent attempts to read these pages use decryption and thus return invalid data

**Comment by mbdavid** [comment]
Hi @spodskubka, you are absolute right. As I read issue title I get same idea: initial size create pages with no encryption... and this can b viewed here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/LiteEngine.cs#L279

Thanks, I will fix soo (it's just add encrypt method call)

**Comment by spodskubka** [comment]
Any performance concerns when writing 50 MB of encrypted vs. unencrypted empty pages?
Since AES is used that shouldn't be an issue, right?

**Comment by mbdavid** [comment]
There is not big difference between encrypted vs. unencrypted performance (~10%). I made a test (in v3) using different operations with/without encryption. You can see times here:

https://github.com/mbdavid/LiteDB-Perf
