### ISSUE TITLE
Unable to cast object of type 'LiteDB.IndexPage' to type 'LiteDB.DataPage'

### ISSUE THREAD

**Issue by Kiritsu** [mbdavid/LiteDB#994]
Hello! I recently get this error when I'm trying to insert an entity:
```cs
System.InvalidCastException occured. Error message: Unable to cast object of type 'LiteDB.IndexPage' to type 'LiteDB.DataPage'. Stack trace:
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   at LiteDB.DataService.Insert(CollectionPage col, Byte[] data)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at Fox.Core.Database.Managers.UserManager.CreateUser(UserEntity entity) in C:\Users\Allan\Desktop\VS Projects\Fox\src\Fox.Core\Database\Managers\UserManager.cs:line 49
```

The line 49 correspond to this method:
```cs
private void CreateUser(UserEntity entity)
{
    Db.Users.Insert(entity);
}
```
where Users is 
```cs
public LiteCollection<UserEntity> Users { get; set; }
```
defined this way:
```cs
using (var db = new LiteDatabase("Fox.db"))
{
    Users = db.GetCollection<UserEntity>();
}
```

and UserEntity is
```cs
public class UserEntity
{
    public ObjectId Id { get; set; }
    public ulong UserId { get; set; }

    public DateTime ClaimedAt { get; set; } = DateTime.Now;
    public long Reputation { get; set; }
    public long Experience { get; set; }
    public long Fox { get; set; }

    public long Level
    {
        get { return Convert.ToInt64(Math.Sqrt(525 + 85 * Experience) / 65); }
    }
}
```

Any idea why this is happening? When I entirely reset the db I can't reproduce :/

Also: this doesn't happen for every new entities...

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
